### ISSUE TITLE
react-color does not work in iframes

### ISSUE THREAD

**Issue by zaslavskyv** [zalify/easy-email#144]
We're hosting the email editor in an iframe, so the users cannot change color of the text because of this bug: https://github.com/casesandberg/react-color/issues/798. There's a fix: https://github.com/casesandberg/react-color/pull/801 but the react-color package doesn't seem to be maintained anymore.

**Comment by m-Ryan** [comment]
Please provide a full working example, I will check later.

**Comment by zaslavskyv** [comment]
Please nevermind — we've updated the email editor to the latest version and the problem appears to be fixed. Thank you!
