### ISSUE TITLE
Question about mj-raw component

### ISSUE THREAD

**Issue by greensouth** [zalify/easy-email#145]
Shouldn't it return
`const { data } = params;
    return <BasicBlock params={params} tag="mj-raw">{data.data.value.content}</BasicBlock>;`
instead of:
` return <BasicBlock params={params} tag="mj-raw" />;`

I tried the component and no value is added to the mjml source.

**Comment by m-Ryan** [comment]
Thanks, the bug has been fixed

**Comment by greensouth** [comment]
> Thanks, the bug has been fixed, please update to the latest version.
> 
> ```
> yarn add easy-email-core@latest easy-email-editor@latest easy-email-extensions@latest
> ```

yay!! Thank you for the fix and for such an AAAAAAAAAAAAAAAAAAAAAAAAWESOME tool!
