### ISSUE TITLE
create template with HTML is possible?

### ISSUE THREAD

**Issue by nyousefzai** [zalify/easy-email#147]

**Comment by m-Ryan** [comment]
Do you mean using HTML mode？
Text block and Raw block can edit HTML.  You can wrap HTML code with these blocks. CSS content  can be placed in the 
 Page data.value.`extraHeadContent `  , detail see https://github.com/zalify/easy-email/blob/master/packages/easy-email-core/src/blocks/standard/Page/index.tsx.
 
demo: https://email.maocanhua.cn/editor?id=1227

![image](https://user-images.githubusercontent.com/20615214/189531912-84650061-7a9a-423f-8df1-e3fde04a1e52.png)
![image](https://user-images.githubusercontent.com/20615214/189531936-c087dcb0-08a4-4f9c-be36-67121ee34042.png)
