### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by turkdemir** [zalify/easy-email#151]
Hi @m-Ryan ,
What can we do for localization? 
Do you have a plan for language support in the nearest future. Or do you have a suggestion for this option.
Thanks.

**Comment by m-Ryan** [comment]
In roadmap planning, but I am busy recently and will not add it in the near future.
If you need to use it, my suggestion is to modify it after fork. Localization is not very complicated, just need to extract all the keywords for translation and replacement.

**Comment by turkdemir** [comment]
Could you please give a clue for _"extract all the keywords"_.
Sincere.

**Comment by m-Ryan** [comment]
For example
1. Mark all keywords as t("xxx")
2. Write a RegExp to extract all t("xxx") to  generate json and i18n,
3. window.t = (xxx)=>i18n[xxx]

**Comment by AlexeyGDataSpike** [comment]
@m-Ryan @turkdemir I added translations easy-email please check this pr in my fork 
https://github.com/zalify/easy-email/pull/158

**Comment by m-Ryan** [comment]
Thanks for @AlexeyGDataSpike , but we already have plans to do it, maybe it will be easier.

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/195236422-412e60aa-9fd4-43f1-beda-76eb6a292691.png)

See https://easy-email-git-feature-localization-m-ryan.vercel.app/editor

Localization is in progress, can anyone help me with the rest?
Just  mark all keywords as t("xxx"), like

```tsx
<div style={{ height: 40, lineHeight: '40px' }}>{t('Configuration')}</div>

```
And I will do the rest of the translation work together.
If you have google services accounts, you can also run scripts/translate.ts to do the rest of the translation

**Comment by mikicho** [comment]
@m-Ryan Is this include localization helpers for the emails as well? or only for the email editor?

**Comment by m-Ryan** [comment]
Only for the email editor. 
I think it is enough to use mergetags for email localization, and replace it when sending

**Comment by mikicho** [comment]
Sounds reasonable. Thanks!

**Comment by turkdemir** [comment]
Hi @m-Ryan ,
I was busy with another job, now I'm back. How can i help you with the localization.

**Comment by m-Ryan** [comment]
Thank turkdemir.
Here is an example https://github.com/zalify/easy-email/pull/214.

In easy-email-core package, you need to import { t } from I18nManager, and mark all texts as t("xxx").
In easy-email-editor and easy-email-extension, t is already mounted on window, so just mark all texts as t("xxx").

For some special cases:
 - If there are variables in the text,  need to write as ` t('Insert before ***', title)`, `***` is a placeholder for variables
 - if the declaration is not in react, need to use getter. For example 
```tsx
export const Page = createBlock<IPage>({
  get name() {
    return t('Page');
  },
  type: BasicType.PAGE,
...
```

If you are interested in the details of the specific implementation, you can check out this. https://github.com/zalify/easy-email/pull/213

**Comment by turkdemir** [comment]
Hi @m-Ryan ,
I finished my work, if you give me access i can send a new branch that consist localization work.

**Comment by m-Ryan** [comment]
@turkdemir Invitation sent, please check your email

**Comment by turkdemir** [comment]
I did my pull request. I created "en" and "tr" json files.
One thing:
i didnt use variables like  t('Insert before ***', title).
This need only existed in one file : HoverTooltip.tsx. (Line 103-109)
so as not to make mistake, i seperated "t" and variable. If you wish, change this lines with variable version or keep it.

**Comment by turkdemir** [comment]
Hi,
i installed last version from npm but i couldnt able to see translated locales of new added items. Old ones works fine. For exampla "Font family" is working but "Font size" not. Do you know what is the matter? @m-Ryan

**Comment by m-Ryan** [comment]
Now it has been merged to master, but the latest version has not been released, we need more time to test. Might be next week.
Check here https://email.maocanhua.cn/
