### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by MohsinAther** [zalify/easy-email#152]
This repository has done some excellent work. i have cloned the repository and examples as well, its running fine on my local machine. 

I'm trying to add a custom block and have already seen an example of a custom block provided in the code but it's not showing the block. I've searched in all previous comments on the repo and couldn't find any help.

Basically, I need a block where I can provide the option to select records from my database via API and render Html as an output. I have seen a text block which allows you to write HTML but I want to generate HTML via my custom code and import it.

**Comment by turkdemir** [comment]
check this, may be help:
https://github.com/zalify/easy-email/issues/134

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email/blob/master/demo/src/pages/Editor/components/CustomBlocks/ProductRecommendation/index.tsx#L90-L92
