### ISSUE TITLE
Changing Block Icon

### ISSUE THREAD

**Issue by sacidaksoy** [zalify/easy-email#153]
Hello Ryan, 
  I wanted to change block icons, I figure out replacing the css contents with selector can works fine
  
```
  .icon-number:before {
  content: '\f468';
  font-family: "Font Awesome 6 free"; 
	font-weight: 900;
}
```
Yes, it is.. 
but I don't know what to do to add and change a new block, class names are the same of that icons. Is there a way to accomplish this situation?
![Ekran görüntüsü 2022-10-04 143911](https://user-images.githubusercontent.com/95652465/193810452-31090433-f4fc-4ed0-8cd7-59f435ae21a1.png)

**Comment by realmail-editor** [comment]
https://www.iconfont.cn/
You can use iconfont to reconfigure a new set of icons, which may be a bit complicated

**Comment by sacidaksoy** [comment]
I changed a little bit of my code block with helps of CSS, then it works.

Solution: 
```
._blockItem_1ajtj_6:nth-last-child(1) .iconfont::before {
  content: '\f04d';
  font-family: "Font Awesome 6 free"; 
	font-weight: 900;
}

._blockItem_1ajtj_6:nth-last-child(2) .iconfont::before {
  content: '\f468';
  font-family: "Font Awesome 6 free"; 
	font-weight: 900;
}
```

Thank you, anyway.
