### ISSUE TITLE
Panel Attribute Sections

### ISSUE THREAD

**Issue by sacidaksoy** [zalify/easy-email#154]
Hello Ryan, 
  How can I create such a sectionable panel, Can you give me hint or suggestions please?

![Ekran görüntüsü 2022-10-04 151450](https://user-images.githubusercontent.com/95652465/193817678-1f30104a-8bfe-4342-b34f-ab6259f85bfd.png)

Example from Button Block panel..

Sincerely.

**Comment by realmail-editor** [comment]
https://github.com/m-Ryan/easy-email-demo/blob/main/src/CustomBlocks/MyFirstBlock/Panel.tsx
check this

**Comment by sacidaksoy** [comment]
Thanks..
https://ant.design/components/collapse/
-> That one worked.
