### ISSUE TITLE
Manipulate Standart Blocks Panel

### ISSUE THREAD

**Issue by sacidaksoy** [zalify/easy-email#155]
Hello Ryan,
  Do we have the possibility to add or remove the panels of the blocks?
  
  I my Case: 

![Ekran görüntüsü 2022-10-04 165145](https://user-images.githubusercontent.com/95652465/193837542-bdac440e-221e-4d09-9707-cf379750dc43.png)

I wanted to change background image of the Hero block from panel.
Do you suggest me any solution or idea? Let me know please.
Best Regards.

**Comment by realmail-editor** [comment]
You can add or overwrite

```tsx
import { BlockAttributeConfigurationManager } from 'easy-email-extensions';

BlockAttributeConfigurationManager.add({
  [BasicType.TEXT]: () => <div>will be overwrite `Text`</div>,
});

```

**Comment by m-Ryan** [comment]
```tsx
import { BlockAttributeConfigurationManager } from '@extensions/AttributePanel/utils/BlockAttributeConfigurationManager';

function NewHeroPanel() {
  const Com = BlockAttributeConfigurationManager.get(AdvancedType.HERO);
  return (
    <div>
      <p>Header</p>
      <Com />
      <p>Footer</p>
    </div>
  );
}

BlockAttributeConfigurationManager.add({
  [AdvancedType.HERO]: NewHeroPanel,
});

```

**Comment by sacidaksoy** [comment]
thanks..

**Comment by sacidaksoy** [comment]
> ```tsx
> import { BlockAttributeConfigurationManager } from '@extensions/AttributePanel/utils/BlockAttributeConfigurationManager';
> 
> function NewHeroPanel() {
>   const Com = BlockAttributeConfigurationManager.get(AdvancedType.HERO);
>   return (
>     <div>
>       <p>Header</p>
>       <Com />
>       <p>Footer</p>
>     </div>
>   );
> }
> 
> BlockAttributeConfigurationManager.add({
>   [AdvancedType.HERO]: NewHeroPanel,
> });
> ```

This method looks like has some kind of a bug. When I applied, my browser tab is freezes.

**Comment by m-Ryan** [comment]
Please update easy-email-extensions@4.3.5 

```bash
yarn add easy-email-extensions@latest
```
And try this
```tsx

const Com = BlockAttributeConfigurationManager.get(AdvancedType.HERO);

function NewHeroPanel() {
  return (
    <div>
      <p>Header</p>
      <Com />
      <p>Footer</p>
    </div>
  );
}

BlockAttributeConfigurationManager.add({
  [AdvancedType.HERO]: NewHeroPanel,
});


```
