### ISSUE TITLE
Merge tags selectbox is hidden below text toolbox

### ISSUE THREAD

**Issue by ketys-from-meiro** [zalify/easy-email#157]
Tried rn on https://email.maocanhua.cn/editor and after clicking on merge tags the selection is below the text toolbox so it's impossible to click on certain values.

<img width="366" alt="Screenshot 2022-10-06 at 10 29 02" src="https://user-images.githubusercontent.com/68279944/194262563-0033517b-241a-4e4f-9ae6-c361d7e9e4de.png">

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/194325634-bc9597d6-4a59-42d9-8c9a-df8ef58f54a1.png)

Cannot be reproduced.

**Comment by ketys-from-meiro** [comment]
@m-Ryan ok, took me a while to find it again lol
Trying to do it on Chromium 106.something, so really up to date browser.

Steps to reproduce on blank template:
1) Add text block
2) Go back to blocks (Back arrow button next to "Configuration")
3) Click into text block to get text toolbar again
4) Click on merge tags

**Comment by m-Ryan** [comment]
Thanks. Please update easy-email-extensions@4.3.5

```bash
yarn add easy-email-extensions@latest
```

**Comment by ketys-from-meiro** [comment]
@m-Ryan thanks, seems like it's resolved! gj
