### ISSUE TITLE
Change the Content of Merge Tags

### ISSUE THREAD

**Issue by sacidaksoy** [zalify/easy-email#159]
Hello Ryan,
  Is there any way to edit the content of the dropdown menu?
  
  See below ScreenShot;
  
![Ekran görüntüsü 2022-10-08 130107](https://user-images.githubusercontent.com/95652465/194702461-8d236b33-a1dc-4f5c-ad67-2ff274ab92fe.png)

Sincerely.

**Comment by sacidaksoy** [comment]
Also I want to add this merge option.. To my Custom Block Button.

![Ekran görüntüsü 2022-10-08 130448](https://user-images.githubusercontent.com/95652465/194702511-071c5065-ab93-4305-a2b9-6d59572ae2fb.png)

**Comment by m-Ryan** [comment]
See renderMergeTagContent
https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-editor/src/components/Provider/PropsProvider/index.tsx

and 
https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-extensions/src/AttributePanel/components/attributes/MergeTags.tsx

**Comment by sacidaksoy** [comment]
I tried this.., couldn't figure out how to use it.
```
<TextField
    label='Content'
    name={`${focusIdx}.data.value.title`}
    mergeTags={testMergeTags}
  />
```
How can I achive this goal with my custom button TextField, or what should I use inside my panel?

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/components/blocks/Button/index.tsx

You can see how the panel of the button block is implemented

**Comment by sacidaksoy** [comment]
Thank you Ryan, it helped a lot.
Sincerely.

**Comment by sacidaksoy** [comment]
Is there any way to change the header title of the merge Tag? Rather than used to "merge tags" string..
![Ekran görüntüsü 2022-10-24 142601](https://user-images.githubusercontent.com/95652465/197515404-f857c0d6-bbf1-40cf-96e8-7e08b7e45905.png)

**Comment by m-Ryan** [comment]
Currently not, if the localized feature is completed, all text can be replaced.
If you are interested, you can go ahead and do the rest.
https://github.com/zalify/easy-email/issues/151
