### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by ketys-from-meiro** [zalify/easy-email#163]
Hi there, I have two issues related to responsiveness:

- the first one is that it cannot be placed in "wrapper" container which has slightly smaller width than a browser window, could it be maybe possible to specify `width` as property?
- the second one is that in up to date version it seems like the sidebar content doesn't fit well. There should be 3 categories on each row, instead there are two and weirdly aligned. Also as you can see the columns picking in layout section overflows. I've tried in latest chromium and safari, implemented in clean `create-react-app` installation using React 17.0.2
<img width="1079" alt="Screenshot 2022-10-21 at 13 34 07" src="https://user-images.githubusercontent.com/68279944/197187292-be71723e-d2c6-455c-a67a-66c9cb6072a8.png">

Code looks simple: 
```
import React from "react";
import { BlockManager, BasicType, AdvancedType } from "easy-email-core";
import { EmailEditor, EmailEditorProvider } from "easy-email-editor";
import { ExtensionProps, StandardLayout } from "easy-email-extensions";

import "easy-email-editor/lib/style.css";
import "easy-email-extensions/lib/style.css";
import "@arco-themes/react-easy-email-theme/css/arco.css";

const categories: ExtensionProps["categories"] = [
  {
    label: "Content",
    active: true,
    blocks: [
      { type: AdvancedType.TEXT },
      {
        type: AdvancedType.IMAGE,
        payload: { attributes: { padding: "0px 0px 0px 0px" } },
      },
      { type: AdvancedType.BUTTON },
      { type: AdvancedType.SOCIAL },
      { type: AdvancedType.DIVIDER },
      { type: AdvancedType.SPACER },
      { type: AdvancedType.HERO },
      { type: AdvancedType.WRAPPER },
      { type: AdvancedType.SECTION },
    ],
  },
  {
    label: "Layout",
    active: true,
    displayType: "column",
    blocks: [
      {
        title: "2 columns",
        payload: [
          ["50%", "50%"],
          ["33%", "67%"],
          ["67%", "33%"],
          ["25%", "75%"],
          ["75%", "25%"],
        ],
      },
      {
        title: "3 columns",
        payload: [
          ["33.33%", "33.34%", "33.33%"],
          ["25%", "25%", "50%"],
          ["25%", "50%", "25%"],
          ["50%", "25%", "25%"],
        ],
      },
      {
        title: "4 columns",
        payload: [["25%", "25%", "25%", "25%"]],
      },
    ],
  },
];

const initialValues = {
  content: BlockManager.getBlockByType(BasicType.PAGE)!.create({}),
};

export default function Email() {
  return (
    <EmailEditorProvider
      data={initialValues}
      height={"calc(100vh - 145px)"}
      autoComplete
      dashed={false}
    >
      {({ values }) => (
        // @ts-ignore
        <StandardLayout compact={false} showSourceCode categories={categories}>
          <EmailEditor />
        </StandardLayout>
      )}
    </EmailEditorProvider>
  );
}
```

Unrelated issue: maybe it would be good to consider some css modules for implementation as it breaks my app layout if it's not integrated into clean create-react-app installation - there can be classnames collisions (there is in my case).

**Comment by ketys-from-meiro** [comment]
The second issue is caused by missing `box-sizing: border-box` properties, for example here:
```
._blockItem_1ajtj_6 ._blockItemContainer_1ajtj_16 {
    width: 96px;
    height: 96px;
    padding: 10px;
    text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    box-sizing: border-box;
}
```

but also to elements for columns layout
<img width="465" alt="Screenshot 2022-10-24 at 11 46 02" src="https://user-images.githubusercontent.com/68279944/197498608-d8c4d2d6-54db-403a-a1b4-dbc3c1101b5a.png">

**Comment by m-Ryan** [comment]
Thanks for your feedback,.
For the first point, it was caused by setting 100vw, we will fix it in the next version. 
For the second point, unfortunately, non-shadow dom is easy to cause style override, and there is no particularly good way.

**Comment by ketys-from-meiro** [comment]
@m-Ryan thanks for the first thing, will appreciate the fix!
re second: so there's no way that css styles would be applied to some wrapper like `.email-editor-wrapper` and wouldn't override global stylesheet? 🤔 I anyway had to do it, wrapped the editor into another div and apply `.email-editor-wrapper * { box-sizing: border-box; }`
Rn. also arco does some resets to html/body which breaks layout of my app a bit.

**Comment by m-Ryan** [comment]
1. I have removed the 100vw limit, please update to the latest version.
```tsx
yarn add easy-email-core@latest easy-email-editor@latest easy-email-extensions@latest
```
2. Most UI libraries will have problems with style overrides, but we need a lot of UI components, so we still need to use . Not a good idea for css reset unless it's all custom UI components.
If you have a good idea, please feel free to tell me.
