### ISSUE TITLE
Q: JSON->MJML and MJML->JSON flow

### ISSUE THREAD

**Issue by ketys-from-meiro** [zalify/easy-email#166]
Hi there, we have a python backend and I would like to ask one thing:
- is it possible to store only MJML transcription of some template on backend?

So far it seems to me that it's viable option because I was able to do JSON->MJML and then MJML->JSON without noticing any template changes. Are the transformations deterministic, wouldn't something break with more difficult template layout?

Thanks!

**Comment by m-Ryan** [comment]
If you are not using custom blocks and logic (if-else/for-each...etc), it works. But this is generally not recommended, storing JSON will make you more scalable
