### ISSUE TITLE
HTML Import

### ISSUE THREAD

**Issue by sacidaksoy** [zalify/easy-email#168]
Hello Ryan, we already had MJML import thanks to you..
   Is there any way to import as HTML?
   
reference ( useImportTemplate ) =>

![Ekran görüntüsü 2022-10-27 145037](https://user-images.githubusercontent.com/95652465/198276991-af022acc-6cfa-408d-9291-82b79ee590c2.png)

**Comment by m-Ryan** [comment]
Maybe you should try Text block.  Import  html code as Text block content

https://documentation.mjml.io/#ending-tags
```tsx
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-family="Helvetica" color="#F45E43">
          <h1>Title</h1>

          <p>Paragraph</p>
          <p style="font-family:Comic Sans Ms">Another paragraph</p>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

```

**Comment by sacidaksoy** [comment]
Thanks, Ryan
