### ISSUE TITLE
How to Change AddToCollection Component 

### ISSUE THREAD

**Issue by XfinitySoft** [zalify/easy-email#171]
Hi @m-Ryan 

We want to change the [AddToCollection](https://github.com/zalify/easy-email/tree/master/packages/easy-email-extensions/src/components/AddToCollection) component.

We are using [Demo](https://github.com/m-Ryan/easy-email-demo) version for the development.

We have two questions:
1 - Is it possible to override the [AddToCollection](https://github.com/zalify/easy-email/tree/master/packages/easy-email-extensions/src/components/AddToCollection) component?
2 - If yes then How we can override it?

Reason to do this:
We are saving collections in the Database so when the user clicks on Add button we want to add a loader to the button and hide the popup when a response is received from a server. 

As we know AddToCollection component is used by [hooks](https://github.com/zalify/easy-email/tree/master/packages/easy-email-extensions/src/hooks) and import in multiple places so our question is: 
How we can override the component so all the imports get the updated version of the component?

We have also sent you an email so can you please respond to our email as well?
Thank You

**Comment by m-Ryan** [comment]
AddToCollection can not be overwrite yet, but implementation is not complicated，PR is welcome. @XfinitySoft
