### ISSUE TITLE
Trim whitespace from links

### ISSUE THREAD

**Issue by zaslavskyv** [zalify/easy-email#172]
If <pre>    http://google.com</pre> is entered in the link target, the generated email will keep the URL whitespaces, making the URL incorrect in some email clients. The link targets should probably be trimmed.

![Screen Shot 2022-11-02 at 10 05 05](https://user-images.githubusercontent.com/83005319/199448855-6ebea308-370e-4329-9b51-285715358cba.png)

**Comment by m-Ryan** [comment]
Please update
```tsx
yarn add  easy-email-extensions@4.3.8
```

**Comment by zaslavskyv** [comment]
Thank you so much!
