### ISSUE TITLE
layer didn't support compact={false}

### ISSUE THREAD

**Issue by zhangchengkk** [zalify/easy-email#175]
when i set compact={false}, layer has nothing and showSourceCode={false} doesn't work.

**Comment by m-Ryan** [comment]
Please update to 
```tsx
yarn add easy-email-extensions@4.3.9
```

**Comment by zhangchengkk** [comment]
it still doesnt work. [codesandbox preview](https://codesandbox.io/p/github/zhangchengkk/easy-email-demo/draft/sweet-mclaren?selection=%5B%7B%22endColumn%22%3A38%2C%22endLineNumber%22%3A216%2C%22startColumn%22%3A38%2C%22startLineNumber%22%3A216%7D%5D&file=%2Fpackage.json)

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/202084569-5616b934-d082-4976-a006-ab45f315197c.png)

Need to update it.
