### ISSUE TITLE
Couldn't use this as a CDN package in html

### ISSUE THREAD

**Issue by shithee** [zalify/easy-email#177]
Is there any way to use this awesome email editor as a CDN package in html.

I have tried to use it using JSdelivr cdn package, but this doesn't works

<script type="module" defer src="https://cdn.jsdelivr.net/npm/easy-email-editor@4.3.7/lib/index.min.js"></script>

**Comment by m-Ryan** [comment]
Please provide a codesanbox demo.

**Comment by shithee** [comment]
When i included the files, its giving the exports error.
please have a look at it.

https://codesandbox.io/s/throbbing-snowflake-0otspn?file=/index.html

Also Can we use the below Functions in our custom blocks

`
import { BasicBlock } from '@core/components/BasicBlock'; // for the custom block element render
import { Width } from '@extensions/AttributePanel/components/attributes/Width'; // For custom block panel
`

If we can use these functionalities, it would be great.

**Comment by m-Ryan** [comment]
Sorry, I don't know much about CDN package, it seems not very simple so far.

**Comment by shithee** [comment]
ok, Thanks for the awesome plugin.
