### ISSUE TITLE
Hide option in the layers tab not hiding the elements

### ISSUE THREAD

**Issue by timbrownls20** [zalify/easy-email#187]
Hi

Hide option in the layers tab not hiding the elements

Steps to reproduce:-

- Drag a hero to the template builder

- Click on Layers tab and  to click on hide option.
![image](https://user-images.githubusercontent.com/20048601/206349317-48b0f134-9c70-492b-8ccc-0805e45885a3.png)

It does not seem to be working in the new version whereas it was functional in the old version of template builder

![image](https://user-images.githubusercontent.com/20048601/206349456-ef087a9f-65eb-49db-ab70-85eb8560ee1b.png)

I've checked your demo site and the issue us the same there

Many Thanks

Tim B

**Comment by m-Ryan** [comment]
Thanks. Please update 
 - easy-email-core@4.3.10
 - easy-email-editor@4.3.10

**Comment by m-Ryan** [comment]
Relatived:https://github.com/zalify/easy-email/pull/189/commits/7d59cecbc3dd511321bacdf960a4a0cf2e279e92

**Comment by timbrownls20** [comment]
brilliant - that's fix it. Thank you
