### ISSUE TITLE
Undo function doesn't respond to removing elements correctly

### ISSUE THREAD

**Issue by timbrownls20** [zalify/easy-email#188]
Hi -Undo function doesn't respond to removing elements correctly

Steps to reproduce:-

- Click on edit to edit an existing template

- Drag an element (say hero) to the template builder

- Click on undo button

- Drag another element (say Image) to the template builder

- Click on undo again

Observation:-

Undo removed image but brings back Hero. 

Expectation:-

Hero was removed from the template so undo shall not add it back to the template

Confirmed it's an issue on the demo site - https://email.maocanhua.cn/editor?id=834&userId=107

**Comment by m-Ryan** [comment]
Thanks. Please update 
 - easy-email-core@4.3.10
 - easy-email-editor@4.3.10

**Comment by m-Ryan** [comment]
Relatived:https://github.com/zalify/easy-email/pull/189/commits/7d59cecbc3dd511321bacdf960a4a0cf2e279e92

**Comment by timbrownls20** [comment]
Brilliant - confirmed fixed. Thank you
