### ISSUE TITLE
block attribute configuration can't show error

### ISSUE THREAD

**Issue by zh1314** [zalify/easy-email#192]
![image](https://user-images.githubusercontent.com/13436139/208233481-18964167-3945-45fb-b9e1-7f30fd490787.png)

why add noStyle
i can't show error now!

or is there have any other idea to show error

now i display error like this

`
const field = useField(name)
<Field helpText={field.meta.error} />
`

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-extensions/src/AttributePanel/components/attributes/Width.tsx

Try validate

**Comment by m-Ryan** [comment]
Can't not show error is a bug.
Please update to easy-email-extensions@4.4.0  
```tsx
yarn add easy-email-extensions@latest
```
Relatived:https://github.com/zalify/easy-email/pull/193

**Comment by zh1314** [comment]
hi，You seem to have forgotten to add the datepickerfield back

![image](https://user-images.githubusercontent.com/13436139/208300246-b183395e-c2af-4e73-9286-516e036699df.png)

**Comment by m-Ryan** [comment]
Thanks, but no need for datepicker.
