### ISSUE TITLE
Enable the appDir option in next.js 13, easy-mail does not work correctly

### ISSUE THREAD

**Issue by wh5938316** [zalify/easy-email#194]
When I enable the appDir option in next.js 13, easy-mail does not work correctly.
Perhaps it is not appropriate to render multiple html tags within a single page, maybe we should replace the html tags with something else in the browser, or use an iframe to wrap them.
![image](https://user-images.githubusercontent.com/16160933/208832311-f4444555-cc96-4715-86d8-ef3cb5e5326c.png)

**Comment by m-Ryan** [comment]
Please check if just modifying the html tags can solve this problem? Maybe the body tag also has an effect.
I'll edit it when you have the result.
