### ISSUE TITLE
mergeTags helper for some attributes

### ISSUE THREAD

**Issue by alexmateos** [zalify/easy-email#195]
How can I add the mergeTags helper for some attributes? 
For example, In the button component, its by default on the name attribute but there is no helper for the HREF attribute.

I also would like to have it for links. Dont k now if I should use text component for this or change it to a custom component.

Can you help me please?

![image](https://user-images.githubusercontent.com/5480073/208861235-770746a2-750f-4f8c-aa12-4263c268271e.png)

**Comment by m-Ryan** [comment]
You can  raise a PR to add the mergeTags helper or  overwrite button panel by your self.

```tsx
import { BlockAttributeConfigurationManager } from 'easy-email-extensions';

BlockAttributeConfigurationManager.add({
  [BasicType.BUTTON]: () => <div>will be overwrite `button`</div>,
});
```
