### ISSUE TITLE
Email preview isn't working

### ISSUE THREAD

**Issue by wagnerlduarte** [zalify/easy-email#196]
For some reason, when I updated the package `easy-email-editor` from `4.3.10` to `4.3.11` the email preview feature stopped working well and only show an empty preview 😢 

It happens for desktop and mobile preview.

Could you help me?

![image](https://user-images.githubusercontent.com/17439470/209023348-0ccdfaba-18fc-43ef-999c-4d205fc19bf3.png)

**Comment by m-Ryan** [comment]
Works fine in [example](https://email.maocanhua.cn/editor?id=834&userId=107). Can you provide more detailed information?

**Comment by wagnerlduarte** [comment]
> Works fine in [example](https://email.maocanhua.cn/editor?id=834&userId=107). Can you provide more detailed information?

I created this [codesandbox](https://codesandbox.io/s/determined-rubin-yznb6d) to simulate the problem.

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/209136166-96381fcc-9c85-4d06-9bb5-a25af11039b7.png)
How to reproduce？

**Comment by wagnerlduarte** [comment]
> ![image](https://user-images.githubusercontent.com/20615214/209136166-96381fcc-9c85-4d06-9bb5-a25af11039b7.png) How to reproduce？

Sorry, I changed the version of the package to test and forgot it 😞 
New if you check, probably the preview is not working https://codesandbox.io/s/determined-rubin-yznb6d

**Comment by m-Ryan** [comment]
Sorry，it's a bug and has been fixed.
Please update to easy-email-editor@4.4.1

Relatived: https://github.com/zalify/easy-email/pull/198
