### ISSUE TITLE
How to add custom text inside Text block on button click?

### ISSUE THREAD

**Issue by Roopaish** [zalify/easy-email#199]
I want to have a button that when clicked should insert a text like {{ user.firstName }} inside the Text block at the point where my cursor is.

Let's say I have this Text block
```
Dear [my_cursor_is_here], thank you.
```

When the button is clicked, it should become
```
Dear {{ user.firstName }} , thank you.
```

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-extensions/src/components/Form/RichTextToolBar/components/MergeTags/index.tsx

https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-extensions/src/components/Form/RichTextToolBar/components/Tools/Tools.tsx

1. 
```tsx
<div onMouseDown={
(ev)=>{
  ev.preventDefault(); // Keep selection range
  document.execCommand('insertHTML', false, "{{ user.firstName }}");
}
}>button</div>
```

2. 
```tsx
     const html = getShadowRoot().activeElement?.innerHTML || ''; // Get new content
     onChange(html); // change value

```
