### ISSUE TITLE
Why isn't BasicBlock exported?

### ISSUE THREAD

**Issue by mikicho** [zalify/easy-email#202]
IIUC, `BasicBlock` is the basic component of all other components. So why can't we use it to build new components? How can we create, for example, a new `<mj-button>` component without using the provided `Button` block?

**Comment by m-Ryan** [comment]
Why do you need to create a new `mj-button`,  the provided Button block is completely aligned with MJML.

**Comment by mikicho** [comment]
The main is that I wanted to create a custom Table component with fixed design. When I tried to use the existing one the browser stuck at the moment I was dropped the component into the email template:
```
createCustomBlock({
...
render:() =>{
return<Table></Table>
}
})
```

**Comment by m-Ryan** [comment]
Can you provide a demo? It shouldn't happen like this.

**Comment by mikicho** [comment]
I can't reproduce this, probably I did something silly. Closing this for now. thanks!

**Comment by mikicho** [comment]
For reference, The problem was that I created a `CustomBlocksType` value with an already existing name (`table`):
```
export enum CustomBlocksType {
  TABLE = 'table', <-- 'table' is already existing! 
}
```

@m-Ryan not sure if this is by design, but it's not a big deal and there is an easy workaround. it was pretty difficult to understand what the problem was.
