### ISSUE TITLE
MergeTags producs wrong tags if custom block has value.dataSource

### ISSUE THREAD

**Issue by mikicho** [zalify/easy-email#207]
```js
export const myBlock = createCustomBlock({
  name: 'MyBlock',
  type: CustomBlocksType.MY_BLOCK,
  validParentType: [AdvancedType.COLUMN],
  create: payload => {
    const defaultData = {
      type: CustomBlocksType.MY_BLOCK,
      data: {
        value: {
          dataSource: 'data.example', <-- This must be different than "dataSource" for MergeTags to work
        },
      },
      attributes: {},
      children: [],
    };
    return merge(defaultData, payload);
  },
  render: (params) => {
    const { data, idx, mode, context, dataSource } = params
    return (
      ....
    );
  },
});
```

It loops over the datasource string value.
This line: https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-extensions/src/utils/getContextMergeTags.ts#L19

![image](https://user-images.githubusercontent.com/11459632/212011658-656c11f0-13e0-4e4e-b1ea-e8f7913440c9.png)

**Comment by m-Ryan** [comment]
It's a hidden logic...
https://github.com/zalify/easy-email/blob/e0b53e051a8a36e817d7d9f0fbba6b49a00b1322/packages/easy-email-extensions/src/utils/getContextMergeTags.ts

**Comment by mikicho** [comment]
> It's a hidden logic...

What do you mean? maybe we should prevent using `dataSource` in custom blocks?

**Comment by m-Ryan** [comment]
Yes, it is currently not recommended to use the dataSource keyword, and there will be specific features related to it later
