### ISSUE TITLE
placeholder feature request

### ISSUE THREAD

**Issue by parathan-velaris** [zalify/easy-email#209]
Thanks for this amazing library. It helps a lot in creating templates without having much to customize.

We need something like placeholder that we can put while writing the template body and then when selecting the suitable template for email, we can able to get those placeholder value and from there we can map those.

**Comment by renyuanz** [comment]
@parathan-velaris thanks for your feedback and support! Can you give me a more specific use case where a "placeholder" would make the most sense? Sketches will definitely help.

**Comment by parathan-velaris** [comment]
can we add a dynamic merge tags while creating template and is there any way to extract those tags while saving? (Does through MJML can we get those tags?)

**Comment by m-Ryan** [comment]
Of course you can use mergetag，Just write a regex to extract `{{xxx}} `

**Comment by parathan-velaris** [comment]
Thanks @m-Ryan. It works as I expected. But I need to clarify the following things whether we can do with easy-email

The following SS has merge tags that were inserted using a Input form;

Merge Tags in Text Toolbar
<img width="567" alt="Capture2" src="https://user-images.githubusercontent.com/117165366/214137171-f36b9659-779e-4d0e-81b8-b3761be1cdd4.PNG">

Input Form:
<img width="188" alt="Capture2" src="https://user-images.githubusercontent.com/117165366/214137433-b96dc3e6-13e9-4924-b98f-8aee34d3ee6e.PNG">

Adding through Input Form and getting it through merge tags is working fine.

But, when we delete a one mergetag it removes from Text toolbar, but How we can remove if we have that merge tag in the email body already? Any in-built feature there?

**Comment by parathan-velaris** [comment]
Hey, may I get a quick response on this? I am curious on this to know whether there are any inbuilt things in the library or do we need to handle those through our-self?

**Comment by parathan-velaris** [comment]
I did the manual extraction using handlebars to extract the merge tags that were written manually in the template. So, I am closing this. Thanks for the quick reply and helping us.
