### ISSUE TITLE
values not updated on first click on editor (non-compact mode)

### ISSUE THREAD

**Issue by Lien-Cheng** [zalify/easy-email#210]
Hi

It seems like when a `non-compact` mode editor just got rendered, if the first click on the component is on the editor's text block (or even other blocks?) and starts modifying the text, the values are actually not updated (can check json)

I'm not sure whether this is an expected behavior or not, just asking

- version: 4.4.2
- also behaves like this in the [examples](https://email.maocanhua.cn/)' non-compact mode (small screen)

thanks!

**Comment by m-Ryan** [comment]
Please update to the latest version 4.4.3
