### ISSUE TITLE
Export MJML not working on demo?

### ISSUE THREAD

**Issue by Robw94** [zalify/easy-email#215]
Was just trying out the dynamic data demo, when clicking 'export HTML or export mjml' the template variables are not replaced when chucking them into a html/mjml viewer.

Am I doing something wrong? I have not changed anything on the link, just wanted to see if it replaced the merge tags on export

[https://email.maocanhua.cn/editor?id=834&userId=107](url)

**Comment by m-Ryan** [comment]
The mergetag in the demo is only used as variables. The exported template does not do the replacement step.
To replace template variables, just add the following code.
![image](https://user-images.githubusercontent.com/20615214/214994954-70f62bb9-ed6a-4e5e-934c-e53a5677332f.png)
