### ISSUE TITLE
Throwing error as "Server Error ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by Raghu-M-S** [zalify/easy-email#216]
After installing package just ran in front-end

**Comment by wagnerlduarte** [comment]
> After installing package just ran in front-end

Hello @Raghu-M-S !
Have you installed the `easy-email` in a server-side rendering project?
Maybe this answer can help you: https://github.com/zalify/easy-email/issues/88#issuecomment-1043453584

**Comment by m-Ryan** [comment]
> @wagnerlduarte I tried that but it's throwing Hydration error

Please provide an code sanbox example for us to check.

**Comment by m-Ryan** [comment]
Can not import easye-email on the server side. 
Please make it as a component and import it dynamically.

```tsx
import dynamic from "next/dynamic";

```

Relatived: https://github.com/zalify/easy-email/issues/88

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/20615214/215327707-402df112-7533-4437-9c8e-d56441c8d1d6.png">

**Comment by realmail-editor** [comment]
But your code sanbox is wrong, please update it and I will check again

**Comment by m-Ryan** [comment]
But your code sanbox is wrong, please update it and I will check again.
