### ISSUE TITLE
How to enable iteration and use merge tags in it?

### ISSUE THREAD

**Issue by ketys-from-meiro** [zalify/easy-email#220]
Hi there, I'm struggling to find where I can enable this iteration settings for blocks?
<img width="360" alt="Screenshot 2023-02-03 at 13 28 13" src="https://user-images.githubusercontent.com/68279944/216603780-e194c085-e827-47b7-918d-270925b99980.png">

And once it's enabled, how I can use merge tags in inner elements? Imagine I have a column which has to be iterated according to `products` tag and I wanna use `title` and `image` attributes inside. Currently it's possible to selected using merge tags only specific attributes directly, like `products[0].title` which is not the thing I wanna achieve (I wanna somethings like `products[].title` or whatever it will be, idk).

Thanks for your response!

**Comment by m-Ryan** [comment]
1.  `enabledLogic` 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/20615214/216631808-d601b2cc-83a9-48f3-bd47-13031a60b0f8.png">

2. Check this example 
https://email.maocanhua.cn/editor?id=834&userId=107

Fill in the array variable of mergetags in `Data source`,
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/20615214/216632491-f282c3a2-49d7-41c0-a4e1-9546d5c69d13.png">

**Comment by ketys-from-meiro** [comment]
@m-Ryan thanks! I see so you then have to fill manually placeholders like `{{item.title}}` and `{{item.price}}` etc without using merge tags text toolbox. Makes sense. 
The bad thing here is that I cannot select `column` in DnD editor and `Layer` component is blank when you're using `StandardLayout` with `compact` set to `false`. Can you take a look into that?

**Comment by m-Ryan** [comment]
Thanks, the bug has been fixed, please update to the latest version and check agagin.

**Comment by ketys-from-meiro** [comment]
Cool, thanks!
