### ISSUE TITLE
Expose a base z-index value to support rendering the email editor inside a modal/dialog

### ISSUE THREAD

**Issue by wilau2** [zalify/easy-email#223]

**Comment by wilau2** [comment]
Still looking into how to override the merge tags z-index.. 
<img width="175" alt="image" src="https://user-images.githubusercontent.com/5473183/217387238-9f4af934-ce90-4d49-bf7a-10769fe0c3cf.png">

**Comment by wilau2** [comment]
I'll make some more tests tomorrow, maybe by moving the portal reference at the root of my project..

**Comment by m-Ryan** [comment]
> I've been able to override:
> 
> ```
> .arco-trigger {
>     z-index: 9999;
> }
> ```
> 
> // theme, If you need to change the theme, you can make a duplicate in https://arco.design/themes/design/1799/setting/base/Color import '@arco-themes/react-easy-email-theme/css/arco.css';
> 
> From the arco website the theme is not duplicatable <img alt="image" width="337" src="https://user-images.githubusercontent.com/5473183/217333566-55b77fef-189d-439b-a2dc-76fdbfa7e660.png">

It looks like arco made a change. Please check agins
<img width="508" alt="image" src="https://user-images.githubusercontent.com/20615214/217451411-0d1aba0b-d1c7-4b18-9ed3-60dbe5b41fed.png">

**Comment by wilau2** [comment]
The copy button is available now thanks ✅ 

I'm still looking into how to fix the FIXED_CONTAINER_ID z-index to display above

**Comment by wilau2** [comment]
Ok got it working... z-index does not work on position static. 
```
  div#FIXED_CONTAINER_ID {
    position: relative;
    z-index: 9999;
  }
  ```
