### ISSUE TITLE
Question: Would it be possible to document the way you publish the package?

### ISSUE THREAD

**Issue by wilau2** [zalify/easy-email#227]
Would it be possible to document the way you publish the package? 

**Context**
I wanted to generate a patch package while waiting for a new release of the lib and my diff was way bigger than expected. 
( I have only used yarn build so far)

You can also explain it in this issue and I can contribute back the documentation. 

Thanks 😗

**Comment by m-Ryan** [comment]
Only need to
```
yarn build
lerna publish
```
The big difference in diff may be a formatting problem. There is a difference between windows and mac line breaks.

**Comment by thijs-qv** [comment]
If I want to just build the packages but not publish them to the NPM registry, `yarn build` should be enough, right?
Should I be then able to import the packages from the compiled code placed in the `lib` directory of each package?

**Comment by m-Ryan** [comment]
Yes, builds are generated in the lib directory of each package
