### ISSUE TITLE
Update OverlayScrollbars to v2

### ISSUE THREAD

**Issue by KingSora** [zalify/easy-email#235]
Currently [easy-email](https://github.com/zalify/easy-email) uses v1 of [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars). v2 was released recently and has a lot of improvements compared to v2. (Focus on modern browsers, 50% smaller size, treeshaking, deferred initialization and many more).
A full list of features and changes can be found [here](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars/CHANGELOG.md).

**Comment by m-Ryan** [comment]
PR is welcome.

**Comment by wilau2** [comment]
Maybe we could let issues like that open an see if we can get contributions
