### ISSUE TITLE
It's seems like there is trouble with the builder

### ISSUE THREAD

**Issue by mduvernon** [zalify/easy-email#242]
While building the libs and importing in other project it's seems like the generated components are not generated in the same way as in development mode,
In the attached image the hilighted section does not interact or disapear 

![easy-email](https://user-images.githubusercontent.com/12007807/219900197-8bdd419e-7953-48c2-a8b6-a8bdb9d303d4.png)

**Comment by m-Ryan** [comment]
Provide a codesanbox reproduction, the referenced package can be from lib
