### ISSUE TITLE
Column background image does not show in editor

### ISSUE THREAD

**Issue by thijs-qv** [zalify/easy-email#244]
Just like a Section, a background image can be set for a Column. While the Section shows the background image in the editor, the Column does not.

**Comment by m-Ryan** [comment]
https://documentation.mjml.io/#mj-column
Column does not have a background image, easy-email is based on MJML.

**Comment by thijs-qv** [comment]
Alright, thanks for explaining. The attributes panel for Column does show the background image option though.
![column-block-attributes-panel](https://user-images.githubusercontent.com/52537741/220610710-c5fe8865-c796-43f7-8e7d-9d215337c81e.png)

**Comment by m-Ryan** [comment]
We'll fix it this week.

**Comment by m-Ryan** [comment]
The latest version has been fixed. I have replaced "background" with "background color".
