### ISSUE TITLE
Editing font size in top bar causes fontSize in right panel to malfunction

### ISSUE THREAD

**Issue by thijs-qv** [zalify/easy-email#245]
If you create a Text element and change the fontSize via the top bar, and then try to adjust the fontSize via the input field in the right panel, the space around the text changes in size instead of the font size.

**Comment by m-Ryan** [comment]
I didn't understand `change the fontSize via the top bar`

**Comment by thijs-qv** [comment]
I mean the toolbar that is shown at the top of the editor when a block is selected. I've added some screenshots for clarification:

when a Text block is selected, you can adjust the fontSize via either

the attributes panel
![text-block-attributes-panel](https://user-images.githubusercontent.com/52537741/220609729-35d128a8-cd25-4646-aed4-4c310e0440c9.png)

or the top bar (toolbar?)
![text-block-toolbar](https://user-images.githubusercontent.com/52537741/220609828-4a47f4b4-b22d-47bb-96fd-33ae957eda54.png)

If I first use the toolbar to select a fontSize, changing the fontSize via the attributes panel does not work any more.

**Comment by thijs-qv** [comment]
I said "doesn't work any more" but it still adjusts the spacing above and below the text, but not the fontSize itself. That is happening because of the fontSize of the block being set?

**Comment by m-Ryan** [comment]
Because of  line-height ?

**Comment by m-Ryan** [comment]
Line height = 1=> 100% font-size => block font size 

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/20615214/221345681-9d5256af-819f-4ad0-80e6-41f184a6abe8.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/20615214/221345689-f7aad2e4-1be1-4c58-8a2d-9fd8b230ba02.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/20615214/221345701-909310df-51a7-4ff1-ad58-ea7165e922da.png">

**Comment by thijs-qv** [comment]
Okay that makes sense, thanks for the clarification!
