### ISSUE TITLE
Merge tags does not appear in dark theme

### ISSUE THREAD

**Issue by arashn0uri** [zalify/easy-email#246]
Hello,

I try to use merge merge tag in dark mode, but I can not use them based on a problem with the theme. Can you check, please?

Thank you
![Screenshot 2023-02-21 at 15 43 19](https://user-images.githubusercontent.com/110023107/220376307-6a3f33a9-309c-471a-8d61-1a1189ac0fb6.png)
![Screenshot 2023-02-21 at 15 44 09](https://user-images.githubusercontent.com/110023107/220376330-3021f839-9dfd-4c1d-8b1f-7def921ab4e5.png)

**Comment by m-Ryan** [comment]
Looks like a bug, we'll fix it this week

**Comment by m-Ryan** [comment]
The latest version has been fixed. Please check.

**Comment by wilau2** [comment]
@m-Ryan issue id fixed on master when I run `yarn dev` 

Releases > 4.7.0 does not seem to have been released properly (we can't see those version on npm)

**Comment by m-Ryan** [comment]
Please check 4.8.0.

**Comment by wilau2** [comment]
It works
