### ISSUE TITLE
API response data remain same between multiple Product block or Custom blocks

### ISSUE THREAD

**Issue by tohin-coderex** [zalify/easy-email#252]
I dropped a Product block and select the Product type from the configuration panel. Everything is working fine and got my expected values. 

![Screenshot](https://user-images.githubusercontent.com/124237022/221118833-8ab0b33a-e7ed-441c-a726-716362a1a809.png)

But if i dropped another Product block, then all the values from the first block are changed. This means, if I have two Product blocks on the editor and fetching data from API, then making changes on one block effects the second one also. Check the Screenshot please

![Screenshot23](https://user-images.githubusercontent.com/124237022/221119492-fc01ef95-118a-418c-9013-f0aac4589309.png)

Whats the main reason behind this?

**Comment by m-Ryan** [comment]
I suspect that the same object has been modified. Take a look at how you wrote your block code.

**Comment by tohin-coderex** [comment]
Thanks for your quick response @m-Ryan. If you have coding example,  sharing with me will be great.

**Comment by m-Ryan** [comment]
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/20615214/221345365-7fdd8408-ef3e-4023-be57-64cc5da7565e.png">

Maybe it's the problem, I updated the demo.

**Comment by tohin-coderex** [comment]
Hello @m-Ryan, as you suggested, I also use mergeBlock instead of merge. Unfortunately, this is not the solution. For better communication, I am sharing my workflow in depth:

1. Dropping a product block on the editor and selecting a category name from the block panel
   
![Select category](https://user-images.githubusercontent.com/124237022/221461774-48838d18-43cd-478c-a5ef-3fe25cbdffb6.png)

2. After the category selection products are coming from API response and rendering perfectly as my expectation 
   
![Products API response](https://user-images.githubusercontent.com/124237022/221461909-a67f27c5-989a-4a69-a406-299ab597aabf.png)

3. Now, if I drop another product block, all selected products from the first product block are restored like defaultValue.
  
![Data restored](https://user-images.githubusercontent.com/124237022/221462155-184bc14a-6381-43e4-b79a-2328c20e7f9a.png)

4. Now, let's select a category for the second product block. What products needed to render on the second block, they are also rendering on the first block as well. Here is the main conflict that occurs. You can see that preview images are also missing on the second product block.
   
![Data conflicts](https://user-images.githubusercontent.com/124237022/221462619-5f0c9de8-a0d1-4ded-a57b-05f92ea488b6.png)

5. Even the Category selection for the first block is still there as my expectation
    
![category selection remain same](https://user-images.githubusercontent.com/124237022/221462989-a9d58441-4771-421a-b18d-a8676b299eb6.png)


For your better understanding, i am sharing some screenshots of my codes as well

1. Product block render 
   
![carbon (2)](https://user-images.githubusercontent.com/124237022/221463473-8911d058-8332-44e3-a498-e2eafdba592c.png)

2. Block panel
   
![carbon (3)](https://user-images.githubusercontent.com/124237022/221463679-b603ddfb-66f1-4e7e-8949-e3ef0837499f.png)



3. DataFetcher component which is used to fetch products from the API and set on the dataSoucre variable
   
![carbon (4)](https://user-images.githubusercontent.com/124237022/221464080-13a49192-a33a-4977-ab23-82eb31e8da39.png)


This is all i have to share with you. Now if have another workaround to solve this problem, please share it with me.

**Comment by m-Ryan** [comment]
The code is too long. Perhaps you can create a minimal reproducible example and use a code sandbox to check it.

**Comment by huannn1** [comment]
It's not related to the issue here. I really like the way you re-structure the editor with Main header with view modes and action buttons, some buttons (Move, Parent, Delete,..) at 2 sides of the active block, how did you do that ? @tohin-coderex 
Thank you!
