### ISSUE TITLE
execCommand is deprecated / execCommand alternative

### ISSUE THREAD

**Issue by thijs-qv** [zalify/easy-email#262]
`packages/easy-email-extensions/src/components/Form/RichTextToolBar/components/Tools/Tools.tsx` adjusts the HTML attributes using `document.execCommand()` but this function is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). Are there any plans to change this implementation?

Also, how would one go about changing this? The reason I ask is because I wanted to add some more fontSizes to the list shown in the toolbar, but found out that changing the fontSize using execCommand only takes an integer value of 1 - 7.

**Comment by m-Ryan** [comment]
Currently, it can be done through [selection range](https://developer.mozilla.org/en-US/docs/Web/API/Selection), but it may be more complicated. 
Before the deprecation of document.execCommand, we may switch to [slate.js](https://www.slatejs.org/) to ensure that the core remains unchanged as much as possible. However, there is currently no plan.

**Comment by thijs-qv** [comment]
Thanks for the info!
