### ISSUE TITLE
Handle selection for CustomBlock that has 2 images with wrapper is an empty tag

### ISSUE THREAD

**Issue by huannn1** [zalify/easy-email#270]
As I understand "getPreviewClassName" function is used to handle Configuration Panel selection for a CustomBlock. In my case, I need to create a CustomBlock (it's actually 2 images) that will be injected into a column, so I don't want to have a wrapper tag for my images so I let it be wrapped by an empty tag. 

But with an empty tag, it doesn't work with Configuration Panel because there is no getPreviewClassName function. It works only with Layer!
So do you have any solution to enable Configuration Panel this case?

![Recording 2023-03-13 143444](https://user-images.githubusercontent.com/11222195/224637520-489abc63-6298-4b03-be49-e853b2624ab6.gif)

Here is my CustomBlock:
```
export const ContentCard = createCustomBlock({
  name: 'Content Card',
  type: CustomBlocksType.CONTENT_CARD,
  validParentType: [BasicType.COLUMN, AdvancedType.COLUMN],
  create: payload => {
    const defaultData = {
      type: CustomBlocksType.CONTENT_CARD,
      data: {
        value: {},
      },
      attributes: {},
      children: [],
    };
    return mergeBlock(defaultData, payload);
  },
  render: ({ data, idx, mode, context, dataSource }) => {
    const { title, buttonText, quantity, footerUrl, bodyUrl } = data.data.value;
    return (
      <>
        <Image
          align="center"
          height="auto"
          padding="0"
          width="302px"
          src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_bodySmall2x_w620xh872.png"
          href={bodyUrl}
        />
        <Image
          align="center"
          height="auto"
          padding="0"
          width="302px"
          src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_footerSmall2x_w620xh88.png"
          href={footerUrl}
        />
      </>
    );
  },
});

**Comment by m-Ryan** [comment]
If you know what you're doing, you can do

```tsx

render: ({ data, idx, mode, context, dataSource }) => {
    const { title, buttonText, quantity, footerUrl, bodyUrl } = data.data.value;

    if (mode === 'testing') {
      retutn (
        {`<div class="${getPreviewClassName(...)}">`}
          <Image
            align="center"
            height="auto"
            padding="0"
            width="302px"
            src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_bodySmall2x_w620xh872.png"
            href={bodyUrl}
          />
          <Image
            align="center"
            height="auto"
            padding="0"
            width="302px"
            src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_footerSmall2x_w620xh88.png"
            href={footerUrl}
          />
        {`<div>`}
      )
    }

    return (
      <>
        <Image
          align="center"
          height="auto"
          padding="0"
          width="302px"
          src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_bodySmall2x_w620xh872.png"
          href={bodyUrl}
        />
        <Image
          align="center"
          height="auto"
          padding="0"
          width="302px"
          src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_footerSmall2x_w620xh88.png"
          href={footerUrl}
        />
      </>
    );
  },

```

**Comment by huannn1** [comment]
Thanks for your suggestion. I can use Column as a wrapper for testing mode and it works.

**Comment by huannn1** [comment]
Just another question, is there a way to use a React component (that is not in easy-email-core's components) in Testing mode ? 
I've tried with an iframe and it doesn't show up

**Comment by m-Ryan** [comment]
It is not clear where you are using, need more detailed information, it is better to give the code

**Comment by huannn1** [comment]
Sorry for missing the code

You can check how I imagine the code, render function in a CustomBlock. I just want to use iframe as a Preview in my project.

`render: ({ data, idx, mode, context, dataSource }) => {
    const { title, buttonText, quantity, footerUrl, bodyUrl } = data.data.value;

    if (mode === 'testing') {
      return  (
      <iframe src="https://something.com" />
      )
    }

    return (
      <>
        <Image
          align="center"
          height="auto"
          padding="0"
          width="302px"
          src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_bodySmall2x_w620xh872.png"
          href={bodyUrl}
        />
        <Image
          align="center"
          height="auto"
          padding="0"
          width="302px"
          src="https://portalvhdszpw30pbh6c7nc.blob.core.windows.net/plugilo/20230310/640af62479e59b7e501eaeb9_footerSmall2x_w620xh88.png"
          href={footerUrl}
        />
      </>
    );
  },`

**Comment by huannn1** [comment]
Thanks for your response
I've tried with your suggestion using iframe in testing mode. It seems when dragging my CustomBlock into the layout, in works incorrectly!
![Recording 2023-03-16 214733](https://user-images.githubusercontent.com/11222195/225656306-c3b521ee-3c97-4cf7-9c8d-dd9942fb3a2f.gif)


Here is my code (I also tried with <Section> with parentType WRAPPER)
```
    if (mode === 'testing') {
      return (
        <Column
          padding={0}
          css-class={
            mode === 'testing' ? getPreviewClassName(idx, data.type) : ''
          }
        >
          <Text>
            {`<iframe
                frameBorder="none"
                src="https://email.maocanhua.cn/"
              />`}
          </Text>
        </Column>
      );
    }
    ```

**Comment by m-Ryan** [comment]
validParentType: [BasicType.Section, AdvancedType.Section],

**Comment by huannn1** [comment]
Even parentType is Section, it still doesn't work properly : (

**Comment by m-Ryan** [comment]
Because the Custom block you dragged is Column. You can't nest inside column.

When you drag first section with two column, like
```tsx
<Section><Column><Column><Column><Column><Section>

```

You can not drag column custom block to here

**Comment by m-Ryan** [comment]
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/20615214/225913992-ac1d909a-62c5-45ba-a1c4-cbf806f04403.png">
https://mjml.io/try-it-live/CnbaqfwFl

@huannn1 

It works  when 
```jsx
<iframe style="width:100px;height:100px" frameBorder="none" src="https://mjml.io/try-it-live/CnbaqfwFl"></iframe>

```
 not 
 
 ```tsx
 <iframe style="width:100px;height:100px" frameBorder="none" src="https://mjml.io/try-it-live/CnbaqfwFl"/>
 
 ```

**Comment by huannn1** [comment]
It works now. Thank you for your great support : )
