### ISSUE TITLE
How to manually assign variables?

### ISSUE THREAD

**Issue by sambegin** [zalify/easy-email#276]
Hello again 👋 

Quick question regarding the editor. I would like to use liquidJS engine to assign variables behind the scene, but it seems the conversion between the WYSIWYG (or JSON) editor and MJML is adding escape char (`&#x27;` ) instead of the real value. Unfortunately, it breaks the engine behind the scene as you can see in my screenshot. 

Is there a way we can bypass this or this would require a fix in the code generating the mjml? 

![Screenshot 2023-03-23 at 10 58 07 AM](https://user-images.githubusercontent.com/6645382/227248676-321552fc-3ab4-4271-91f9-e921b6e7f493.png)
![Screenshot 2023-03-23 at 10 58 43 AM](https://user-images.githubusercontent.com/6645382/227248680-8a573bcd-8563-4da8-9136-a4fa1c1f3903.png)
![Screenshot 2023-03-23 at 10 59 38 AM](https://user-images.githubusercontent.com/6645382/227248682-2648eb5c-449e-4b6a-93b1-a26a52d036ca.png)
![Screenshot 2023-03-23 at 11 08 27 AM](https://user-images.githubusercontent.com/6645382/227248684-fce5cdba-9286-4d19-8cee-12e72085a358.png)

Let me know your thoughts! 

Thank you!

**Comment by sambegin** [comment]
Ok I might have found the reason why it is not working out of the box. This would maybe come down to the lodash's `unescape` function that does not handle more than a couple of unescaped char:

![Screenshot 2023-03-23 at 11 50 52 AM](https://user-images.githubusercontent.com/6645382/227260222-8425f44a-f3f2-4965-8252-dc8418339ed8.png)
![Screenshot 2023-03-23 at 11 51 16 AM](https://user-images.githubusercontent.com/6645382/227260225-b360e0c4-523d-41b0-8701-016990310a11.png)

🤔

**Comment by sambegin** [comment]
PR attempt to fix this: https://github.com/zalify/easy-email/pull/277

**Comment by m-Ryan** [comment]
It has been published to the latest version. Please check

**Comment by sambegin** [comment]
Thanks for the quick response! Closing this issue ✅
