### ISSUE TITLE
Missing fluid-on-mobile attribute

### ISSUE THREAD

**Issue by applibs** [zalify/easy-email#279]
By mjml documentation I missing setting fluid-on-mobile for images in editor.
Or editor do it self automatically?

**Comment by m-Ryan** [comment]
It is indeed missing, we will add it in the next version, and it will be released this week. Thanks.

**Comment by applibs** [comment]
Do you have detailed Roadmap what you will develop in step-by-step?

**Comment by m-Ryan** [comment]
Fluid-on-mobile attribute added to the latest version.
--
No roadmap, the focus now is mainly on fixing some bugs.
