### ISSUE TITLE
Question: How to use EmailEditor without layout?

### ISSUE THREAD

**Issue by sambegin** [zalify/easy-email#287]
Hello! 

We'd like to know if there is a possibility to use the EmailEditor without being wrapped in a Standard or Simple Layout.

Basically: 

```
 <EmailEditorProvider
          data={content}
          dashed={false}
          enabledLogic={false}
          autoComplete
          enabledMergeTagsBadge={false}
          height={'720px'}
          onSubmit={submitTenantTemplate}
        >
          {({ values }, { submit }) => {
          return (
			<EmailEditor />
			)
		}
</EmailEditorProvider>
```

Right now, using this solution doesn't trigger any re-render when we edit the email. Essentially, we'd like to edit only the text within the email, without all the drag n drop / adding / removing email components. 

Let me know if I missed something to make this possible. 

Thank you!

**Comment by m-Ryan** [comment]
I will check this week. The positioning of easy-email-extensions is as a UI library, so it is not necessary.

**Comment by sambegin** [comment]
Thank @m-Ryan . 

In the meantime, I dig a little bit yesterday and came up with the minimal stuff needed to achieve what I wanted: https://github.com/zalify/easy-email/pull/290

Let me know!
