### ISSUE TITLE
Can not run yarn dev

### ISSUE THREAD

**Issue by hainv** [zalify/easy-email#297]
I got error when run yarn dev.
My npm is 
`$ npm -v
9.4.0
`
node is
`$ node -v
v19.6.1
`
`$ yarn dev
yarn run v1.22.19
$ cd demo && yarn dev
$ vite
Pre-bundling dependencies:
  react-dom
  react
  @sentry/browser
  @sentry/tracing
  react-router-dom
  (...and 30 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/lodash/isEqualWith.js:1:26: error: Could not resolve "./_baseIsEqual"
    1 │ var baseIsEqual = require('./_baseIsEqual');
      ╵                           ~~~~~~~~~~~~~~~~

 > node_modules/lodash/get.js:1:22: error: Could not resolve "./_baseGet"
    1 │ var baseGet = require('./_baseGet');
      ╵                       ~~~~~~~~~~~~

 > node_modules/lodash/toNumber.js:1:23: error: Could not resolve "./_baseTrim"
    1 │ var baseTrim = require('./_baseTrim'),
      ╵                        ~~~~~~~~~~~~~

 > node_modules/lodash/isSymbol.js:1:25: error: Could not resolve "./_baseGetTag"
    1 │ var baseGetTag = require('./_baseGetTag'),
      ╵                          ~~~~~~~~~~~~~~~

 > node_modules/lodash/merge.js:1:24: error: Could not resolve "./_baseMerge"
    1 │ var baseMerge = require('./_baseMerge'),
      ╵                         ~~~~~~~~~~~~~~

 > node_modules/lodash/merge.js:2:29: error: Could not resolve "./_createAssigner"
    2 │     createAssigner = require('./_createAssigner');
      ╵                              ~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/_root.js:1:25: error: Could not resolve "./_freeGlobal"
    1 │ var freeGlobal = require('./_freeGlobal');
      ╵                          ~~~~~~~~~~~~~~~

 > node_modules/lodash/mapValues.js:1:30: error: Could not resolve "./_baseAssignValue"
    1 │ var baseAssignValue = require('./_baseAssignValue'),
      ╵                               ~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/mapValues.js:2:25: error: Could not resolve "./_baseForOwn"
    2 │     baseForOwn = require('./_baseForOwn'),
      ╵                          ~~~~~~~~~~~~~~~

 > node_modules/lodash/mapValues.js:3:27: error: Could not resolve "./_baseIteratee"
    3 │     baseIteratee = require('./_baseIteratee');
      ╵                            ~~~~~~~~~~~~~~~~~

 > node_modules/lodash/has.js:1:22: error: Could not resolve "./_baseHas"
    1 │ var baseHas = require('./_baseHas'),
      ╵                       ~~~~~~~~~~~~

 > node_modules/lodash/_hasPath.js:1:23: error: Could not resolve "./_castPath"
    1 │ var castPath = require('./_castPath'),
      ╵                        ~~~~~~~~~~~~~

 > node_modules/lodash/isArguments.js:1:30: error: Could not resolve "./_baseIsArguments"
    1 │ var baseIsArguments = require('./_baseIsArguments'),
      ╵                               ~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/mapKeys.js:1:30: error: Could not resolve "./_baseAssignValue"
    1 │ var baseAssignValue = require('./_baseAssignValue'),
      ╵                               ~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/mapKeys.js:2:25: error: Could not resolve "./_baseForOwn"
    2 │     baseForOwn = require('./_baseForOwn'),
      ╵                          ~~~~~~~~~~~~~~~

 > node_modules/lodash/mapKeys.js:3:27: error: Could not resolve "./_baseIteratee"
    3 │     baseIteratee = require('./_baseIteratee');
      ╵                            ~~~~~~~~~~~~~~~~~

 > node_modules/lodash/snakeCase.js:1:31: error: Could not resolve "./_createCompounder"
    1 │ var createCompounder = require('./_createCompounder');
      ╵                                ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/camelCase.js:2:31: error: Could not resolve "./_createCompounder"
    2 │     createCompounder = require('./_createCompounder');
      ╵                                ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/upperFirst.js:1:30: error: Could not resolve "./_createCaseFirst"
    1 │ var createCaseFirst = require('./_createCaseFirst');
      ╵                               ~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/toString.js:1:27: error: Could not resolve "./_baseToString"
    1 │ var baseToString = require('./_baseToString');
      ╵                            ~~~~~~~~~~~~~~~~~

 > node_modules/lodash/set.js:1:22: error: Could not resolve "./_baseSet"
    1 │ var baseSet = require('./_baseSet');
      ╵                       ~~~~~~~~~~~~

 > node_modules/lodash/cloneDeepWith.js:1:24: error: Could not resolve "./_baseClone"
    1 │ var baseClone = require('./_baseClone');
      ╵                         ~~~~~~~~~~~~~~

 > node_modules/lodash/setWith.js:1:22: error: Could not resolve "./_baseSet"
    1 │ var baseSet = require('./_baseSet');
      ╵                       ~~~~~~~~~~~~

 > node_modules/lodash/omit.js:1:23: error: Could not resolve "./_arrayMap"
    1 │ var arrayMap = require('./_arrayMap'),
      ╵                        ~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:2:24: error: Could not resolve "./_baseClone"
    2 │     baseClone = require('./_baseClone'),
      ╵                         ~~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:3:24: error: Could not resolve "./_baseUnset"
    3 │     baseUnset = require('./_baseUnset'),
      ╵                         ~~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:4:23: error: Could not resolve "./_castPath"
    4 │     castPath = require('./_castPath'),
      ╵                        ~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:5:25: error: Could not resolve "./_copyObject"
    5 │     copyObject = require('./_copyObject'),
      ╵                          ~~~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:6:30: error: Could not resolve "./_customOmitClone"
    6 │     customOmitClone = require('./_customOmitClone'),
      ╵                               ~~~~~~~~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:7:23: error: Could not resolve "./_flatRest"
    7 │     flatRest = require('./_flatRest'),
      ╵                        ~~~~~~~~~~~~~

 > node_modules/lodash/omit.js:8:27: error: Could not resolve "./_getAllKeysIn"
    8 │     getAllKeysIn = require('./_getAllKeysIn');
      ╵                            ~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 31 errors:
node_modules/lodash/_hasPath.js:1:23: error: Could not resolve "./_castPath"
node_modules/lodash/_root.js:1:25: error: Could not resolve "./_freeGlobal"
node_modules/lodash/camelCase.js:2:31: error: Could not resolve "./_createCompounder"
node_modules/lodash/cloneDeepWith.js:1:24: error: Could not resolve "./_baseClone"
node_modules/lodash/get.js:1:22: error: Could not resolve "./_baseGet"
...
    at failureErrorWithLog (C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:1149:7)
    at C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:1258:14
    at C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\Users\MyUser\easy-email\demo\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`

**Comment by m-Ryan** [comment]
You may need to downgrade to node v16

**Comment by hainv** [comment]
I downgrade to `npm -v 8.19.4` and `node -v v16.20.0` but yarn still `yarn run v1.22.19`.
What version are you using?

**Comment by hainv** [comment]
I manual download lodash from `https://www.jsdelivr.com/package/npm/lodash` and untar to both `./node_modules/lodash` and `./demo/node_modules/lodash`. then start `yarn dev`. It's working.
