### ISSUE TITLE
Default custom font support

### ISSUE THREAD

**Issue by willcuii** [zalify/easy-email#299]
Hello, is there a way to add a custom font family with font host URLs as part of the default font list? currently, the only way I see is to import the font name and link in that `Import font ` section in the bottom right side panel in the UI. But it is not very convenient to do it for every template I have.

**Comment by m-Ryan** [comment]
I think it can be solved by creating each template with custom font.
You have two ways, one is that there are custom fonts in the default fonts. The other is to modify extraHeadContent (the content of extraHeadContent cannot be deleted by the user).

And then, configure your default font, users can quickly select.
![image](https://user-images.githubusercontent.com/20615214/234155033-7e049f2c-7250-41c2-817a-5c9ab12f53b3.png)

Relatived:
https://github.com/zalify/easy-email/blob/master/packages/easy-email-core/src/blocks/standard/Page/index.tsx

// extraHeadContent example
{
  "type": "page",
  "data": {
    "value": {
      "extraHeadContent": " <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>",
      "breakpoint": "480px",
      "headAttributes": "",
      "font-size": "14px",
      "line-height": "1.7",
      "headStyles": [],
      "fonts": [],
      "responsive": true,
      "font-family": "Raleway",
      "text-color": "#000000"
    }
  },
  "attributes": {
    "background-color": "#d6dde5",
    "width": "600px"
  },
  "children": [
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "padding": "20px 0px 20px 0px",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "background-color": "#ffffff"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "width": "50%",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4u.png",
                "href": "https://mjml.io",
                "alt": "Racoon logo",
                "padding": "10px 10px 10px 10px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fa8739",
        "padding": "0px 0px 0px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "width": "200px",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 17px;\">SPRING PROMO</p>\n          <p>50%</p>\n          <p>OFFER</p>\n          <p style=\"font-size: 13px\">Lorem ipsum dolor sit amet, consectetur adipiscing elit<br /></p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#fff",
                "font-size": "40px",
                "padding": "10px 25px 10px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "SHOP NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fff",
                "color": "#fa8739",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "16px",
                "padding": "15px 25px 40px 25px",
                "inner-padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "width": "400px",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "https://assets.maocanhua.cn/57b75a82-e8df-4281-9590-fb9487466d6e-image.png",
                "alt": "Clothes set",
                "border": "none",
                "width": "400px",
                "padding": "0px 0px 0px 0px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#2f323b",
        "padding": "0px 0px 0px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "middle",
            "width": "25%",
            "padding": "10px 0px 10px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4t.png",
                "alt": "Box free shipping",
                "border": "none",
                "width": "42px",
                "padding": "10px 0px 10px 0px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "middle",
            "width": "75%",
            "padding": "10px 0px 10px 0px"
          },
          "children": [
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>FREE SHIPPING ON ORDER <span style=\"font-weight: bold;color: rgb(250, 135, 57);\">OVER 55&#x20AC;</span></p>"
                }
              },
              "attributes": {
                "align": "left",
                "color": "#fff",
                "font-size": "18px",
                "padding": "0px 25px 10px 25px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fff",
        "padding": "20px 0px 20px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {},
            "hidden": false
          },
          "attributes": {
            "border": "none",
            "vertical-align": "bottom",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4v.jpg",
                "alt": "Chesterk tank",
                "border": "none",
                "width": "209px",
                "padding": "30px 0px 20px 0px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>CHESTERK TANK</p>\n          <p style=\"color: rgb(250, 135, 57);\">15&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "font-weight": "bold",
                "color": "#000",
                "font-size": "15px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 30px 10px 30px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "bottom",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4g.jpg",
                "alt": "Beyond backpack",
                "border": "none",
                "width": "178px",
                "padding": "10px 0px 20px 0px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>BEYOND BACKPACK</p>\n          <p style=\"color: rgb(250, 135, 57);\">20&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "font-weight": "bold",
                "color": "#000",
                "font-size": "15px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#612d0a",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 30px 10px 30px",
                "inner-padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fff",
        "padding": "20px 0px 20px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "bottom",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x46.jpg",
                "alt": "Jensen shorts",
                "border": "none",
                "width": "182px",
                "padding": "30px 0px 20px 0px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>JENSEN SHORTS</p>\n          <p style=\"color: rgb(250, 135, 57);\">28&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "font-weight": "bold",
                "color": "#000",
                "font-size": "15px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 30px 10px 30px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "bottom",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4h.jpg",
                "alt": "Verdant cap",
                "border": "none",
                "width": "129px",
                "padding": "20px 0px 20px 0px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>VERDANT CAP</p>\n          <p style=\"color: rgb(250, 135, 57);\">20&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "font-weight": "bold",
                "color": "#000",
                "font-size": "15px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 25px 10px 25px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "bottom",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4i.jpg",
                "alt": "Blake polo shirt",
                "border": "none",
                "width": "208px",
                "padding": "20px 0px 20px 0px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>BLAKE POLO SHIRT</p>\n          <p style=\"color: rgb(250, 135, 57);\">25&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "font-weight": "bold",
                "color": "#000",
                "font-size": "15px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 30px 10px 30px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "bottom",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4j.jpg",
                "alt": "Sketch floral",
                "border": "none",
                "width": "72px",
                "padding": "20px 0px 20px 0px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>SKETCH FLORAL</p>\n          <p style=\"color: rgb(250, 135, 57);\">23&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "font-weight": "bold",
                "color": "#000",
                "font-size": "15px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 30px 10px 30px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fa8739",
        "padding": "0px 0px 0px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4k.jpg",
                "alt": "Man 1",
                "width": "301px",
                "padding": "0px 0px 0px 0px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "width": "50%",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 19px;\">ANDERSON SWEATER</p>\n          <p style=\"font-size: 36px;\">75&#x20AC;</p>\n          <p>The Anderson Sweater features a floral all-over print with contrast colour.</p>"
                }
              },
              "attributes": {
                "align": "left",
                "color": "#fff",
                "font-size": "13px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fff",
                "color": "#fa8739",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "padding": "0px 30px 20px 30px",
                "inner-padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#2f323b",
        "padding": "0px 0px 20px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 19px;\">ALDER TWO JONES JACKET</p>\n          <p style=\"font-size: 36px;\">100&#x20AC;</p>\n          <p>Colour-block design, zip entry, oxford hood lining, side pockets &amp; TC lining.</p>"
                }
              },
              "attributes": {
                "align": "left",
                "color": "#fff",
                "font-size": "13px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "padding": "0px 30px 10px 30px",
                "inner-padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/xj6.jpg",
                "alt": "Man 2",
                "border": "none",
                "width": "302px",
                "padding": "0px 0px 0px 0px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fa8739",
        "padding": "0px 0px 0px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 14px;\">DISCOVER OUR</p>\n          <p style=\"font-size: 27px;\">SUMMER COLLECTION</p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#fff",
                "font-size": "13px",
                "padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fff",
        "padding": "20px 0px 20px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4q.jpg",
                "alt": "Topaz C3 shoes",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>TOPAZ C3 SHOES</p>\n          <p style=\"color: rgb(250, 135, 57);\">70&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#000",
                "font-size": "15px",
                "font-weight": "bold",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "font-size": "13px",
                "padding": "0px 30px 10px 30px",
                "inner-padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4r.jpg",
                "alt": "Camden backpack",
                "border": "none",
                "width": "199px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p>CAMDEN BACKPACK</p>\n          <p style=\"color: rgb(250, 135, 57);\">50&#x20AC;</p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#000",
                "font-size": "15px",
                "font-weight": "bold",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "button",
              "data": {
                "value": {
                  "content": "BUY NOW"
                }
              },
              "attributes": {
                "align": "center",
                "background-color": "#fa8739",
                "color": "#fff",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "120%",
                "target": "_blank",
                "vertical-align": "middle",
                "border": "none",
                "text-align": "center",
                "href": "https://mjml.io",
                "padding": "0px 30px 10px 30px",
                "inner-padding": "10px 25px 10px 25px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#2f323b",
        "padding": "20px 0px 20px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x47.png",
                "alt": "Cards",
                "width": "72px",
                "padding": "10px 25px 10px 25px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 15px;font-weight: bold;\">PAYMENT METHODS</p>\n          <p>We accept all majors payments options</p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#fff",
                "font-size": "13px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x48.png",
                "alt": "Currencies",
                "border": "none",
                "width": "70px",
                "padding": "10px 25px 0px 25px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 15px;font-weight: bold;\">CURRENCIES CHOICE</p>\n          <p>You have the choice to pay with your own currencies</p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#fff",
                "font-size": "13px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "top",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x4y.png",
                "alt": "Express",
                "border": "none",
                "width": "82px",
                "padding": "10px 25px 8px 25px"
              },
              "children": []
            },
            {
              "type": "text",
              "data": {
                "value": {
                  "content": "<p style=\"font-size: 15px;font-weight: bold;\">EXPRESS SHIPPING</p>\n          <p>Delivered tomorrow before noon</p>"
                }
              },
              "attributes": {
                "align": "center",
                "color": "#fff",
                "font-size": "13px",
                "padding": "0px 25px 0px 25px"
              },
              "children": []
            }
          ]
        }
      ]
    },
    {
      "type": "section",
      "data": {
        "value": {
          "noWrap": false
        }
      },
      "attributes": {
        "background-repeat": "repeat",
        "background-size": "auto",
        "background-position": "top center",
        "border": "none",
        "direction": "ltr",
        "text-align": "center",
        "background-color": "#fa8739",
        "padding": "0px 0px 20px 0px"
      },
      "children": [
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "middle",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "image",
              "data": {
                "value": {}
              },
              "attributes": {
                "align": "center",
                "height": "auto",
                "src": "http://191n.mj.am/img/191n/3s/x49.png",
                "alt": "Racoon logo",
                "border": "none",
                "width": "180px",
                "padding": "10px 0px 0px 0px"
              },
              "children": []
            }
          ]
        },
        {
          "type": "column",
          "data": {
            "value": {}
          },
          "attributes": {
            "border": "none",
            "vertical-align": "middle",
            "padding": "0px 0px 0px 0px"
          },
          "children": [
            {
              "type": "social",
              "data": {
                "value": {
                  "elements": [
                    {
                      "href": "[[SHORT_PERMALINK]]",
                      "icon-size": "20px",
                      "target": "_blank",
                      "src": "https://easy-email-m-ryan.vercel.app/images/acbae5eb-efa4-4eb6-866c-f421e740b713-ad3c92b1-9cdb-4a7b-aad3-75ad809db8a3.png",
                      "content": "Facebook",
                      "name": "facebook"
                    },
                    {
                      "href": "[[SHORT_PERMALINK]]",
                      "icon-size": "20px",
                      "target": "_blank",
                      "src": "https://easy-email-m-ryan.vercel.app/images/98520d6c-5cef-449e-bcbf-6316ccec2088-e8780361-0deb-4896-895e-e690c886cdf0.png",
                      "content": "Google",
                      "name": "twitter"
                    },
                    {
                      "href": "[[SHORT_PERMALINK]]",
                      "icon-size": "20px",
                      "target": "_blank",
                      "src": "https://easy-email-m-ryan.vercel.app/images/b064f705-34ba-4400-975e-9dd0cec21c30-cc9aa158-56bd-4bf1-b532-72390d25c864.png",
                      "content": "Twitter",
                      "name": "google"
                    }
                  ]
                }
              },
              "attributes": {
                "align": "center",
                "color": "#333333",
                "mode": "horizontal",
                "font-size": "13px",
                "font-weight": "normal",
                "border-radius": "3px",
                "line-height": "22px",
                "text-padding": "4px 4px 4px 0px",
                "icon-padding": "0px",
                "icon-size": "20px",
                "padding": "20px 25px 10px 25px",
                "inner-padding": "4px 4px 4px 4px"
              },
              "children": []
            }
          ]
        }
      ]
    }
  ]
}
