### ISSUE TITLE
PR proposal

### ISSUE THREAD

**Issue by Nilegfx** [zalify/easy-email#303]
Hi maintainers, 
would you be open to a PR to use jsoneditor in the demo instead of a plain text field? I already had it for my own usage but I thought it would be nice to contribute back to this nice repo. 

![image](https://user-images.githubusercontent.com/1198975/234317180-42bc0a65-3a43-43ad-8139-814128e4180f.png)

please let me know.

**Comment by m-Ryan** [comment]
Thanks Nilegfx. But I think jsoneditor is too heavy, it will make users feel more complicated
