### ISSUE TITLE
border styling for buttons

### ISSUE THREAD

**Issue by parathan-velaris** [zalify/easy-email#305]
I want to provide each properties of border for button separately for convenience.

Like:

Border Width
Border Style
Border Color

but in mj-button (https://mjml.io/compatibility/mj-button) those CSS can not be passed separately.

What would be the approach to make each of the above CSS properties to be work as expected?

**Comment by m-Ryan** [comment]
You have two ways to implement this:
1. Customize a custom block.
2. Split and merge, you can refer to `Padding`.

https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/components/attributes/Padding.tsx

**Comment by parathan-velaris** [comment]
This worked as Expected, Thanks @m-Ryan

**Comment by thijs-qv** [comment]
@parathan-velaris did you end up making a custom component? Would you mind sharing your code?

**Comment by Parathantl** [comment]
@thijs-qv , No there is a component for Border but it accepts like
`1px solid green`

I just changed it with https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/components/attributes/Padding.tsx as how it did In Padding

Refer this and try, I was want only this change

`import React, { useCallback, useEffect, useMemo } from 'react';
import {
  ColorPickerField,
  NumberField,
  SelectField,
  TextField,
} from '../../../components/Form';
import { useFocusIdx, Stack, useBlock, TextStyle, IconFont } from 'easy-email-editor';
import { createBlockDataByType } from 'easy-email-core';
import { Form, useFormState } from 'react-final-form';
import { Button, Grid, Space, Tooltip } from '@arco-design/web-react';
import { get } from 'lodash';
import { pixelAdapter } from '../adapter';
import { borderStyleOptions } from '@extensions/AttributePanel/components/attributes/BorderStyle';

export interface PaddingProps {
  title?: string;
  attributeName?: 'border';
  name?: string;
  showResetAll?: boolean;
}
export function Border(props: PaddingProps = {}) {
  const { title = t('Border'), attributeName = 'border', name, showResetAll } = props;
  const { focusBlock, change, values } = useBlock();
  const { focusIdx } = useFocusIdx();

  const type = focusBlock && focusBlock.type;

  const defaultConfig = useMemo(
    () => (type ? createBlockDataByType(type) : undefined),
    [type],
  );

  const borderValue: any | undefined = useMemo(() => {
    if (name) {
      return get(values, name);
    }
    return focusBlock?.attributes[attributeName];
  }, [attributeName, focusBlock?.attributes, name, values]);

  const defaultPaddingValue: any | undefined = useMemo(() => {
    if (name) {
      return null;
    }
    return defaultConfig?.attributes[attributeName];
  }, [attributeName, defaultConfig?.attributes, name]);

  const paddingFormValues = useMemo(() => {
    const paddingList = borderValue?.split(' ');
    const defaultPaddingList = defaultPaddingValue?.split(' ');

    const width = paddingList ? paddingList[0] : defaultPaddingList?.[0] || '0';
    const color = paddingList ? paddingList[1] : defaultPaddingList?.[1] || '';
    const style = paddingList ? paddingList[2] : defaultPaddingList?.[2] || '';

    return {
      width,
      color,
      style,
    };
  }, [defaultPaddingValue, borderValue]);

  const onChancePadding = useCallback(
    (val: string) => {
      if (name) {
        change(name, val);
      } else {
        change(focusIdx + `.attributes[${attributeName}]`, val);
      }
    },
    [name, change, focusIdx, attributeName],
  );
  const onResetPadding = useCallback(() => {
    if (name) {
      change(name, '0px 0px 0px 0px');
    } else {
      change(focusIdx + `.attributes[${attributeName}]`, '0px 0px 0px 0px');
    }
  }, [name, change, focusIdx, attributeName]);

  return (
    <Form<{ width: number; color: string; style: string }>
      initialValues={paddingFormValues}
      subscription={{ submitting: true, pristine: true }}
      enableReinitialize
      onSubmit={() => {}}
    >
      {() => {
        return (
          <>
            <Stack
              vertical
              spacing='extraTight'
            >

                <Grid.Row>
                  <Grid.Col span={11}>
                    <NumberField
                      label={t('Width (px)')}
                      name='width'
                      config={pixelAdapter}
                    />
                  </Grid.Col>

                  <Grid.Col
                    offset={1}
                    span={11}
                  >
                    <SelectField
                      label={t('Style')}
                      name='style'
                      options={borderStyleOptions}
                    />
                  </Grid.Col>
                </Grid.Row>

              <Grid.Row>
                <Grid.Col span={23}>
                  <ColorPickerField
                    label={t('Color')}
                    name='color'
                  />
                </Grid.Col>
              </Grid.Row>

            </Stack>
            <PaddingChangeWrapper onChange={onChancePadding} />
          </>
        );
      }}
    </Form>
  );
}

const PaddingChangeWrapper: React.FC<{ onChange: (val: string) => void }> = props => {
  const {
    values: { width, color, style },
  } = useFormState();
  const { onChange } = props;

  useEffect(() => {
    onChange([width, color, style].join(' '));
  }, [width, color, style, onChange]);

  return <></>;
};
`
