### ISSUE TITLE
createCustomBlock is not working in JavaScript project, but works in TypeScript project which is shown in demo

### ISSUE THREAD

**Issue by parathan-velaris** [zalify/easy-email#314]
Based on Documentation:
https://github.com/zalify/easy-email/blob/master/packages/easy-email-core/readme.md

I tried adding a new custom block in the demo (https://github.com/zalify/easy-email)

But, the same approach is not working in JavaScript project. The demo uses TypeScript project

**Comment by m-Ryan** [comment]
Please provide more detailed information. There will not be a situation where only typescript is supported but not JavaScript.

**Comment by parathan-velaris** [comment]
hey sorry, that was my mistake where I forgot to import the Custom Block Component declaration into the Editor component. That's why its not loaded and couldn't get it.
