### ISSUE TITLE
Support "full-width" attribute for Section

### ISSUE THREAD

**Issue by huannn1** [zalify/easy-email#316]
I've checked MJML documentation, Section component supports full-width attribute. 
But I can't see there is a setting for that attribute in Section panel.

It would be great if we could have it in Section panel as well.
Thank you!

![image](https://github.com/zalify/easy-email/assets/11222195/dd1a0967-aabf-4479-bfbd-43e37458ec0e)

By using full-width I can make background color of a section is not limited by page width like this
![image](https://github.com/zalify/easy-email/assets/11222195/81aa9246-bbe8-44a0-afe5-89d3d8166e92)

**Comment by m-Ryan** [comment]
In fact, it is supported, but it does not appear in the config panel, you can customize the config panel.
Docs here https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/readme.md

**Comment by huannn1** [comment]
Got it, I'll try to customize the panel for Section. Thank you1
