### ISSUE TITLE
Similarly onUploadImage need onUploadImageRemove function

### ISSUE THREAD

**Issue by parathan-velaris** [zalify/easy-email#318]
When removing the image by clicking Delete option, it needs to trigger a passed function so that I can able to do the deletion of image from server.

Is that possible?

Happy to make a PR if needed but guidance needed

**Comment by m-Ryan** [comment]
Thanks @parathan-velaris .
 Add  onUploadImageRemove, which is at the same level as onUploadImage, you can search for onUploadImage to view.

Handle image remove event in ImageUploader（packages/easy-email-extensions/src/components/Form/ImageUploader/index.tsx）.

**Comment by parathan-velaris** [comment]
@m-Ryan Is that fine to return the URL to the function passed. From there the library users can do the removal of image from their storage server. Correct me if I am wrong

**Comment by Parathantl** [comment]
@m-Ryan , sorry about it. I will create a PR and refer this number, I definitely need this feature to be in the library. It would be helpful to delete the uploaded image
