### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by psmoros** [zalify/easy-email#321]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@chuayupeng) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by chuayupeng** [comment]
@m-Ryan Hi! I am the researcher in question, was just wondering why the issue was closed as completed but the `SECURITY.md` file was not set up yet?

**Comment by chuayupeng** [comment]
@psmoros it seems like the maintainer closed this issue without ever doing up the security.md file, and has not replied my repeated attempts on trying to responsibly disclose this issue.
