### ISSUE TITLE
MJML Source code panel blur breaks the JSON layout code

### ISSUE THREAD

**Issue by sambegin** [zalify/easy-email#325]
Easily reproducible with the demo:  https://email.maocanhua.cn/editor?id=834&userId=107
It seems that all the iterations and conditions blocks are getting replaced by "raw" blocks

- Original: 
<img width="1726" alt="Screenshot 2023-06-14 at 5 13 43 PM" src="https://github.com/zalify/easy-email/assets/6645382/8d1db5b2-4b6e-4b34-9863-546b53e892d8">

- Open MJML source code and only focus it (you do not even need to change anything)
<img width="1728" alt="Screenshot 2023-06-14 at 5 13 50 PM" src="https://github.com/zalify/easy-email/assets/6645382/7a034ec6-d213-4181-884f-dfb4febfadb3">

- Click outside the MJML source code panel (blur), and see how the layout is broken:
<img width="1728" alt="Screenshot 2023-06-14 at 5 13 57 PM" src="https://github.com/zalify/easy-email/assets/6645382/1ff3af0f-2a98-40fb-8139-67f2583ae402">

**Comment by m-Ryan** [comment]
This is expected. Because there is no way to turn the original block into an advanced block

**Comment by m-Ryan** [comment]
Maybe we can change this to read-only. This is for the convenience of the debugger and should not be seen by the user

**Comment by sambegin** [comment]
I see. It really depends on the context of users but on our side in caused more trouble than helped to have this side by there. 
We could potentially have an option to turn read-only on/off for this panel depending on the usage

**Comment by m-Ryan** [comment]
![image](https://github.com/zalify/easy-email/assets/20615214/2a68ca8c-10e6-4701-b507-fc32978cb786)

add mjmlReadOnly at easy-email-extensions@4.12.2

**Comment by fabien-roy** [comment]
I also opened this to allow the same kind of behavior in the JSON editor + having some readonly styles: https://github.com/zalify/easy-email/pull/329

**Comment by sambegin** [comment]
@m-Ryan , There is still an issue with this. Even if we `mjmlReadOnly`, there is a listener happening probably on the "blur" of the mjml container that will still output raw element when we focus out (this seems to be happening only when the root `Page` is focused in the editor.

I would have loved to dig into this and find the solution but it is impossible for me to debug this repository: https://github.com/zalify/easy-email/issues/355

**Comment by m-Ryan** [comment]
The development mode is still the same as before, you don’t need to pay attention to the live website @sambegin
