### ISSUE TITLE
Missing dark mode colors for ContextMenu in BlockLayer

### ISSUE THREAD

**Issue by cytostatic** [zalify/easy-email#331]
![image](https://github.com/zalify/easy-email/assets/10391243/2dfa345e-7064-4b4c-8976-af7d0e3d1bdf)

**Comment by m-Ryan** [comment]
Will fix this week

**Comment by cytostatic** [comment]
Thank you very much

**Comment by m-Ryan** [comment]
![image](https://github.com/zalify/easy-email/assets/20615214/73f228dc-384f-4eb9-b2b4-c25360eadc66)

Please update to
 - easy-email-extensions@4.14.1

**Comment by cytostatic** [comment]
Looks great. Thank you for your quick reply. The issue can be closed.
