### ISSUE TITLE
Mobile Image: How to retain mj tags css-classes in Preview and output

### ISSUE THREAD

**Issue by sarathjasrin** [zalify/easy-email#336]
Hi @m-Ryan ,

I'm trying to add an setting to capture separate image for mobile devices.

I'm able to add and capture the mobile image source. Now I'm trying to media query to replace default image with mobile image in smaller devices

`/easy-email-core/src/blocks/standard/Page/index.tsx
`
 ```
const advancedImages = flatMap(data.children, findAdvancedImages);

    let styleStr = "";

    advancedImages.map(image => {
      if (image.data.value?.mobileImage?.enabled) {
        styleStr += `.node-idx-content.children.[0].node-type-advanced_image { content: url(${image.data.value?.mobileImage?.sourceUrl});
          width: 100%; }`;
      }
    });

    const mobileImages = `<mj-style>
      @media all and (max-width: 480px) {
        ${styleStr}
      }
    </mj-style>`;

```

Here I'm trying to read all image tags and generate media query if they have mobile Image.

**Issue:** To add media query I need unique `css-class`. We do have unique `css-class` in editor window but if we go to preview or export source, those classes are omitted. So I couldn't add media query specifically. 

1.  How I can retain unique `css-class `
2. Or is there any other way I can implement it in a better way. 

Refer: https://github.com/sarathjasrin/easy-email/tree/MobileImage

**Comment by sarathjasrin** [comment]
Hi @m-Ryan, Thanks for the reply. I understand your commercial version has two codes. Can you give me any direction I will dig in to see further. 

And also what is the pricing for the commercial one.

**Comment by m-Ryan** [comment]
I can only say that it's actually quite complicated. If the two pieces of code are not handled properly, it may result in duplication.
I don't want to discuss matters related to the commercial version here.
If you are interested in the commercial version, you can contact me at [962491243@qq.com](mailto:962491243@qq.com).
@sarathjasrin
