### ISSUE TITLE
NextJS 13: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Arsenalist** [zalify/easy-email#342]
I copy-pasted the code from the main example and am receiving the error:

Has anyone encountered this?

```
Unhandled Runtime Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Call Stack
eval
node_modules/easy-email-editor/lib/index.js (6414:0)
```

**Comment by m-Ryan** [comment]
Relatived https://github.com/zalify/easy-email/issues/120
May be related to Strict Mode？Please remove <StrictMode>
@Arsenalist

**Comment by Arsenalist** [comment]
I'm using NextJS and need strict mode to be on.

**Comment by mhamadyhya1** [comment]
hello i have same issue and strict method did not work
