### ISSUE TITLE
Handle local files

### ISSUE THREAD

**Issue by cytostatic** [zalify/easy-email#344]
Hi,
I am developing a MJML editor VSCode extension and i need a possibility to display local files. Is there a way to react on image URL changes to overwrite the src for them?
An async callback function prop on the EmailEditor component for src attributes for image tags would be nice.

**Comment by m-Ryan** [comment]
I'm not familiar with vscode extensions, maybe you need this?
https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static

**Comment by cytostatic** [comment]
yes, that is the plan. But i need a way to enter a filename in the image path input and rewrite the src attribute of the image tag with the object URL.
Therefore an async hook or event is required when the src attribute is set.

**Comment by m-Ryan** [comment]
In this situation, I believe you just need to add an additional property, for example, "local_src." When it changes, you can upload the file and then update the "src" accordingly. @cytostatic

**Comment by cytostatic** [comment]
OK. Thank you very much. I will try this.
