### ISSUE TITLE
Customize DefaultPageConfigPanel component by adding some extra props to TextField

### ISSUE THREAD

**Issue by makavelithadon** [zalify/easy-email#347]
Hi,

First of all thanks for all the amazing work done on this library !

I would like to customize the UI and particularly make the "subject" TextField required (in this file => [packages/easy-email-extensions/src/AttributePanel/components/blocks/Page/index.tsx](https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/components/blocks/Page/index.tsx)) and I did not manage to accomplish it.

I would like to customize a little bit more than `hideSubject` or `hideSubtitle` props (I already read the doc about it)

Have you got some idea please ?

Thanks in advance ^^

**Comment by m-Ryan** [comment]
I think you can rewrite the Page panel, just copy the original code over.

https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/components/blocks/Page/index.tsx

**Comment by makavelithadon** [comment]
Okay, I had already tried what you're suggesting, but I thought there might be another way, perhaps by passing some configuration or something like that.

I'll do as suggested.

Thank you for the response. I close this thread.
