### ISSUE TITLE
combine to block Image and Text in new one without setting panel by hand

### ISSUE THREAD

**Issue by ZdyrkoVlad** [zalify/easy-email#348]
Need to combine to block Image and Text in new one. With standard panel config and settings. So as a result expect to get one block with Images at the top and text at the bottom. And with the all settings that we already have in standard Image and Text. It`s possible? Or need to create a custom block and set the panel by hand?( 
If you have any references to the doc or examples. It's very helpful. Thanks)

**Comment by m-Ryan** [comment]
This isn't complicated; you can refer to the code of the custom block to understand its principles. Then, create a custom block.

https://github.com/zalify/easy-email/blob/master/demo/src/pages/Editor/components/CustomBlocks/index.tsx

**Comment by ZdyrkoVlad** [comment]
Okay, thanks
