### ISSUE TITLE
Extensions Documentation: AttributePanel "You can add or overwrite"

### ISSUE THREAD

**Issue by xstortionist** [zalify/easy-email#349]
Sorry for my ignorance but I'm having a very difficult time understanding how to "add" as it states in the readme for extensions package. 

Example: Would like to add a dimension switch to the section block for being able to add "full-width" attribute.

The documentation example is a bit misleading as it shows you how to replace the entire panel with text, rather than adding to it.

If there is something I could reference that points me in the right direction of how to achieve this, that would be great and in return I do PR to add more detailed documentation to the read.me file in the extensions package.

Thank you for the lovely app, I plan on sticking around and will help out as much as I can.

**Comment by m-Ryan** [comment]
I think it is very complicated to add Field alone in certain places, and different people have different needs. 
It is much simpler to completely overwrite and rewrite. You only need to copy the original Panel code and change it.

**Comment by xstortionist** [comment]
Thanks for the response. Perhaps you could help me identify how to overwrite the panel code and in return I will add the documentation. I took a look around and see there have been a number of other users who have also asked about full width attribute being added to section block. I'm not a power react user so it's easy for me to figure this out without a little push in the right direction. I think in order to grow the community we will want to work on adding documentation for attributes panels with examples that are baked into MJML framework, such as the full width attribute.

I do not mind creating PR and  documenting my process for adding this to the panel.

Thanks for the response, Ryan.

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/components/blocks/Section/index.tsx
```
<TextField name={`${focusIdx}.attributes.full-width`} />
```

Fill  `full-width` .


The easiest way is to copy this file overlay and add a TextField to control the full-width value.
Of course, the best way should be to use SwitchField to control Boolean values
