### ISSUE TITLE
Can make dynamic component from json data ?

### ISSUE THREAD

**Issue by KhanamDEV** [zalify/easy-email#351]
I have a case, affter I export an email template into a json string, can I use that json string to create a custom block? Can I pass json to the `render method` when using `createCustomBlock`?

**Comment by Ngocha2607** [comment]
I have the same problems.

**Comment by m-Ryan** [comment]
Can you describe in detail the reason for doing this?

If different impression types are required, then just multiple conditions are required, e.g.

```tsx
if (ConditionA) {
return <Text />
}
if (ConditionB) {
return <Button />
}

```


If it is completely dynamic, then you need to make a custom block to parse json data into JSX syntax, which is not very complicated.

**Comment by KhanamDEV** [comment]
@m-Ryan  Thank you for reply, I want using object json same below in render method, how can i do it. 
![image](https://github.com/zalify/easy-email/assets/53226018/e47ccdb1-e3ce-4c9b-a5db-83521d4792f4)
![image](https://github.com/zalify/easy-email/assets/53226018/a44e3d84-d9bc-45b3-89be-350685122572)

**Comment by KhanamDEV** [comment]
@m-Ryan I saw function `HtmlStringToReactNodes` but I can not using it. 
![image](https://github.com/zalify/easy-email/assets/53226018/3aa4b51d-b8c4-47fb-9853-1adae70a8a6a)

**Comment by m-Ryan** [comment]
I still don't know your use case. Could you please provide a more specific description?

**Comment by KhanamDEV** [comment]
@m-Ryan I want to create multiple custom blocks (eg header, footer...), then save their json object in the database. And when I open the editor, I want to render those custom blocks to the Custom Block section.
I know when creating a custom block we will have to create jsx files, but is there any way I can get the json object of that template and register it in the custom block?

**Comment by m-Ryan** [comment]
You can define a custom block, store the rendering JSON within children, and then dynamically render based on the children. Its rendering logic would be similar to Section and Column.
