### ISSUE TITLE
Images preview problem

### ISSUE THREAD

**Issue by ZdyrkoVlad** [zalify/easy-email#353]
Hi, could you fix this image's preview issue, please? Or maybe write how to set a custom default image icon.
![image](https://github.com/zalify/easy-email/assets/20615214/ac83cb9b-6ed5-4d20-97c4-b0c52b183bf9)

**Comment by ZdyrkoVlad** [comment]
Posible the problem is this https://easy-email-m-ryan.vercel.app/images/06ca521d-9728-4de6-a709-1b75a828bfc3-2a9b1224-3d71-43b8-b52f-e7cdcdc9107b.png   png. Could you add this image as static to lib? It is be very helpful

**Comment by m-Ryan** [comment]
Check here https://github.com/zalify/easy-email/issues/150

**Comment by ZdyrkoVlad** [comment]
Yep, all good now. Thanks m-Ryan!
