### ISSUE TITLE
How do we run the repository locally to contribute?

### ISSUE THREAD

**Issue by sambegin** [zalify/easy-email#355]
A lot have changed since we've made contribution to this project. Main things are:

- Not even being able to see the project live without giving aways personal information:
![image](https://github.com/zalify/easy-email/assets/6645382/bf5192d8-7217-405e-8d14-0af3b31f47fc)

- Not even being able to run the project locally when cloning it (this is the only thing we see when running `yarn dev`: 
![Screenshot 2023-10-06 at 8 18 48 AM](https://github.com/zalify/easy-email/assets/6645382/05e3532a-459b-4d80-8329-b4960a197d5d)

Why is that? To me, this is compromising a lot the help we can provide to this repository. Is the documentation not up to date? Are the contributions deliberately blocked?

**Comment by m-Ryan** [comment]
![image](https://github.com/zalify/easy-email/assets/20615214/1af0acf7-e0b4-4335-a857-18bc505d3548)

There is no change, the default development is still through the demo directory. Another example (nextjs demo) shows the back-end interaction, including addition, deletion, modification and query.

It has not been submitted to the main repo yet (I still need to check if there are any bugs)

**Comment by sambegin** [comment]
```
$ yarn  
$ yarn install-all
$ yarn dev
```

That's exactly what I'm doing and ending up in the second screenshot posted initially 🤷  (no editor is being presented on localhost:3000, just a laggy "browserless debugger")
