### ISSUE TITLE
Default images are not found

### ISSUE THREAD

**Issue by huannn1** [zalify/easy-email#358]
As the latest code, the default images in the map file are not found (getImg.ts). Is there something updated?
![image](https://github.com/zalify/easy-email/assets/11222195/7da8a30c-5d38-4cf4-b31b-5f93600c1f15)
Thank you

**Comment by timbrownls20** [comment]
same for us. The social images aren't there. Looks like the vercel deployment is down

![image](https://github.com/zalify/easy-email/assets/20048601/ace755fb-0db1-4d11-867f-7361c959f406)

Could the images be put back please

**Comment by m-Ryan** [comment]
Ok, it has been restored. I still recommend that you use ImageManager to overwrite the original image

**Comment by huannn1** [comment]
I will, thank you @m-Ryan
