### ISSUE TITLE
Changing drag and drop default icon

### ISSUE THREAD

**Issue by ZdyrkoVlad** [zalify/easy-email#360]
Hi, how can I change this icon(vector images)? On column and wrapper etc. I already know about image manager. But it doesn`t help. Doues is even possible to use image manager to change that? 
![image](https://github.com/zalify/easy-email/assets/31853587/56e9aabc-6d14-44da-b298-9205da2e5a0b)

Be very thankful for the help

**Comment by m-Ryan** [comment]
Icon is the font and can be changed via classname

check here https://github.com/zalify/easy-email/issues/153

**Comment by ZdyrkoVlad** [comment]
Okay, I will try this. Thanks Ryan!
