### ISSUE TITLE
Layout broke If I don't add antd.css

### ISSUE THREAD

**Issue by Piero87** [zalify/easy-email#364]
Hello,
I have tried the example here in the documentation this:

```
import React from 'react';
import { BlockManager, BasicType, AdvancedType } from 'easy-email-core';
import { EmailEditor, EmailEditorProvider } from 'easy-email-editor';
import { ExtensionProps, StandardLayout } from 'easy-email-extensions';
import { useWindowSize } from 'react-use';

import 'easy-email-editor/lib/style.css';
import 'easy-email-extensions/lib/style.css';

// theme, If you need to change the theme, you can make a duplicate in https://arco.design/themes/design/1799/setting/base/Color
import '@arco-themes/react-easy-email-theme/css/arco.css';

const initialValues = {
  subject: 'Welcome to Easy-email',
  subTitle: 'Nice to meet you!',
  content: BlockManager.getBlockByType(BasicType.PAGE)!.create({}),
};

export default function App() {
  const { width } = useWindowSize();

  const smallScene = width < 1400;

  return (
    <EmailEditorProvider
      data={initialValues}
      height={'calc(100vh - 72px)'}
      autoComplete
      dashed={false}
    >
      {({ values }) => {
        return (
          <StandardLayout
            compact={!smallScene}
            showSourceCode={true}
          >
            <EmailEditor />
          </StandardLayout>
        );
      }}
    </EmailEditorProvider>
  );
}


```

and I have some errors in the rendering of the element inside the page for example:
<img width="1501" alt="Screenshot 2023-11-20 alle 16 46 59" src="https://github.com/zalify/easy-email/assets/768952/ca276139-8dd5-4a29-ab89-795e283147d2">

so I checked this demo: https://github.com/m-Ryan/easy-email-demo and there I can't see the error, so I try to play a bit with the source code of the demo and I see that If I remove the antd.css import the error is the same:

<img width="1510" alt="Screenshot 2023-11-20 alle 16 44 58" src="https://github.com/zalify/easy-email/assets/768952/12c8c616-3071-40ca-90a9-63da1b489459">

so my question is, is antd.css a peerDependecy of the project? 
I would also add that with antd5 they have css in js so antd.css is not importable and it will break in the same way, so antd v4 is the unique way to render it correctly, am I missing something?

Thanks

**Comment by m-Ryan** [comment]
Check if box-sizing is overridden. I think your css is conflicting

**Comment by Piero87** [comment]
@m-Ryan It's not my css is also yours, if you remove the import here in your demo: https://github.com/m-Ryan/easy-email-demo/blob/4631299e964003d80bd9beed1e5fe0695bd38f4c/src/App.tsx#L3C1-L3C52 you will see the same problem
