### ISSUE TITLE
easy-email  incompatible  with outlook  desktop 

### ISSUE THREAD

**Issue by koutatmed** [zalify/easy-email#375]
Hi    
When I send an email with a text font size of 20px, I receive the email with truncated text on Outlook desktop. However, on Outlook's official website, it works fine. I have attached the screenshots of the bug for reference. thanks
![Captu2e](https://github.com/zalify/easy-email/assets/94910935/cf102006-0eb1-4eec-afea-ad5042c5ee10)
![Capture](https://github.com/zalify/easy-email/assets/94910935/e532fc37-d6d4-460c-9e85-8902715fd1d4)

**Comment by m-Ryan** [comment]
easy-email will eventually be converted to MJML. If it is an email compatibility issue, please go to MJML for resolution https://github.com/mjmlio/mjml/issues @koutatmed
