### ISSUE TITLE
Cannot render EmailEditor next13 app dir 

### ISSUE THREAD

**Issue by ihatebeans3000** [zalify/easy-email#376]
`Unhandled Runtime Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
`

but pages route can render. 

is there any solution about this?

**Comment by m-Ryan** [comment]
check this demo https://github.com/m-Ryan/easy-email-nextjs-demo

**Comment by ihatebeans3000** [comment]
@m-Ryan 
thanks for comment 👍

I already tried demo repo, it works! but not working when using only app route..

**Comment by m-Ryan** [comment]
easy email is es module, can not run in sever.

**Comment by ihatebeans3000** [comment]
is there no way using easy email in appDir?
even if using dynamic import?

**Comment by m-Ryan** [comment]
No, appDir is server dir

**Comment by ihatebeans3000** [comment]
Thanks!
