### ISSUE TITLE
Image upload option

### ISSUE THREAD

**Issue by alphasquare123456** [zalify/easy-email#378]
Image upload option is missing in downloaded code can you help

**Comment by m-Ryan** [comment]
![image](https://github.com/zalify/easy-email/assets/20615214/d384d098-0c9f-4683-a0ec-a0a950598aa3)

check this

**Comment by alphasquare123456** [comment]
thank you ,how in which add 
![upload](https://github.com/zalify/easy-email/assets/39161127/f7b09400-b1b3-467c-a215-3e9640c672ba)

**Comment by m-Ryan** [comment]
you need to implement `onUploadImage`

**Comment by alphasquare123456** [comment]
but in demo site is there ,can pls help me to fix and update that upload image option code
