### ISSUE TITLE
When trying to import an Mjml file I exported after building my email there is an error showing

### ISSUE THREAD

**Issue by akramsarkis** [zalify/easy-email#383]
When trying to import an Mjml file I exported after building my email there is an error showing

![Capture d'écran 2024-03-08 162651](https://github.com/zalify/easy-email/assets/82215775/79b51ef7-6c43-4dff-aca7-be5c21527a8c)

I think it needs to be fixed, note that I am not able to attach my mjml file as it is not supported here , I converted it to a zip file

[welcome.zip](https://github.com/zalify/easy-email/files/14540410/welcome.zip)

**Comment by m-Ryan** [comment]
@akramsarkis fixed

**Comment by akramsarkis** [comment]
Just checked and indeed it is fixed, I will make sure of it by importing several files and if all good, I will close this ticket
