### ISSUE TITLE
Can i drag a basic content(text/button etc.) into a custom component?

### ISSUE THREAD

**Issue by Repeg** [zalify/easy-email#385]
![image](https://github.com/zalify/easy-email/assets/11849026/ccf1aee6-3a88-4c7d-93b0-17388bdfd078)

my requirement is to create a custom style block like the screentshot shows(white background with a blue section content), and i want to drag some content into the blue payment section
but i cannot create one throuth default wrapper.

is there any solution?

Thanks!!!

**Comment by Repeg** [comment]
here's  the code: 
return (
      <Wrapper
        background-color={attributes['background-color']}
        padding="30px"
      >
        <Wrapper
          // add class name when testing preview
          css-class={mode === 'testing' ? getPreviewClassName(idx, data.type) : ''}
          border='1px solid #294E95'
          border-radius='10px'
          text-align='center'
          padding="20px"
          margin="30px"
          background-color="#EAEEF5"
        >
        </Wrapper>
      </Wrapper>
    );

**Comment by m-Ryan** [comment]
Just need to change children validParentType

![image](https://github.com/zalify/easy-email/assets/20615214/3cf43279-67f6-455e-903d-c60b238b095e)

**Comment by Repeg** [comment]
Hi @m-Ryan 
i tried to change the value of validParentType but still cannot drag content into custom block.

my file looks like:
![image](https://github.com/zalify/easy-email/assets/11849026/31d124d5-c4ea-47ae-90df-79e590a7cd3c)

and the result looks like:
![image](https://github.com/zalify/easy-email/assets/11849026/45400031-2363-4054-8181-8af1341d3684)


here is my full code:
import {
  IBlockData,
  BasicType,
  components,
  createCustomBlock,
  createBlock,
  getPreviewClassName,
  AdvancedType,
  mergeBlock,
} from 'easy-email-core';

import { CustomBlocksType } from '../constants';
import React from 'react';

import { getContentEditableClassName } from 'easy-email-editor';

const { Column, Section, Wrapper, Text, Button, Image, Group } = components;

export type IPayment = IBlockData<
  {
    'background-color': string;
    'title-color': string;
    title: string;
  }
>;

export const Payment = createCustomBlock<IPayment>({
  name: 'Payment',
  type: CustomBlocksType.PAYMENT,
  validParentType: [
    BasicType.COLUMN,
    BasicType.HERO,

    // BasicType.PAGE,
    // BasicType.WRAPPER,
    // BasicType.COLUMN,
    // BasicType.GROUP,
    // BasicType.HERO,

    // AdvancedType.WRAPPER,
    // AdvancedType.COLUMN,
    // AdvancedType.GROUP,
    // AdvancedType.HERO,
  ],
  create: payload => {
    const defaultData: IPayment = {
      type: CustomBlocksType.PAYMENT,
      data: {
        value: {
          title: '',

        },
      },
      attributes: {
        'background-color': '#ffffff',
        'title-color': '#000000',
        title: '',
      },
      children: [
        {
          type: BasicType.TEXT,
          children: [],
          // validParentType: [
          //   BasicType.PAGE,
          //   BasicType.WRAPPER,
          //   BasicType.COLUMN,
          //   BasicType.HERO,

          //   AdvancedType.WRAPPER,
          // ],
          data: {
            value: {
            },
          },
          attributes: {
          },
        },
      ],
    };
    return mergeBlock(defaultData, payload);
  },
  render: ({ data, idx, mode, context, dataSource }) => {
    const attributes = data.attributes;
    const paymentInfo = data.data.value.paymentInfo;
    return (
      <Wrapper
        background-color={attributes['background-color']}
      // padding="30px"
      >
        <Wrapper
          // add class name when testing preview
          css-class={mode === 'testing' ? getPreviewClassName(idx, data.type) : ''}
          border='1px solid #294E95'
          border-radius='10px'
          text-align='center'
          background-color="#EAEEF5"
        ></Wrapper>
      </Wrapper>
    );
  },
});

export { Panel } from './Panel';

**Comment by m-Ryan** [comment]
Change to 

```
[
BasicType.COLUMN,
BasicType.HERO,
AdvancedType.COLUMN,
AdvancedType.HERO,
]
```

**Comment by Repeg** [comment]
Thanks @m-Ryan  i got this
